#ifndef SC_WEB_UI_H
#define SC_WEB_UI_H

static const char WEB_UI_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>scrcpy AI Control</title>\n"
"<style>\n"
"* { margin: 0; padding: 0; box-sizing: border-box; }\n"
":root {\n"
"  --bg-0: #080b14;\n"
"  --bg-1: #0f1526;\n"
"  --bg-2: #151e33;\n"
"  --card: rgba(17, 25, 44, 0.82);\n"
"  --card-soft: rgba(17, 25, 44, 0.62);\n"
"  --line: rgba(120, 148, 215, 0.25);\n"
"  --text: #ecf0ff;\n"
"  --text-dim: #9aa8cc;\n"
"  --accent: #7b8cff;\n"
"  --accent-2: #36d5ff;\n"
"  --good: #2fd49c;\n"
"  --warn: #ffc857;\n"
"  --bad: #ff5f7d;\n"
"}\n"
"body {\n"
"  font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
"  color: var(--text);\n"
"  background:\n"
"    radial-gradient(1000px 600px at -10% -20%, rgba(54, 213, 255, 0.18), transparent 55%),\n"
"    radial-gradient(900px 500px at 110% 120%, rgba(123, 140, 255, 0.14), transparent 55%),\n"
"    linear-gradient(135deg, var(--bg-0), var(--bg-1) 45%, var(--bg-2));\n"
"  height: 100vh;\n"
"  display: flex;\n"
"  gap: 10px;\n"
"  padding: 10px;\n"
"  margin: 0;\n"
"}\n"
"\n"
"/* Left panel: Remote */\n"
"#panel-remote {\n"
"  flex: 1;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  min-width: 0;\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 16px;\n"
"  overflow: hidden;\n"
"  background: var(--card);\n"
"  backdrop-filter: blur(12px);\n"
"  box-shadow: 0 14px 40px rgba(0, 0, 0, 0.45);\n"
"}\n"
"#video-wrapper {\n"
"  flex: 1;\n"
"  display: flex;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  background: radial-gradient(circle at 50% 10%, #0f1628 10%, #02040a 80%);\n"
"  min-height: 0;\n"
"  position: relative;\n"
"  overflow: hidden;\n"
"}\n"
"#remote-video { max-width: 100%; max-height: 100%; object-fit: contain; display: block; }\n"
"#remote-video.rotated { position: absolute; top: 50%; left: 50%; max-width: none; max-height: none; object-fit: fill; }\n"
"#touch-overlay { position: absolute; inset: 0; cursor: crosshair; touch-action: none; }\n"
"#video-loading {\n"
"  position: absolute;\n"
"  inset: 0;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  background: rgba(0, 0, 0, 0.6);\n"
"  color: var(--text-dim);\n"
"  font-size: 14px;\n"
"  z-index: 10;\n"
"  pointer-events: none;\n"
"}\n"
"#video-loading .spinner {\n"
"  width: 44px;\n"
"  height: 44px;\n"
"  border: 3px solid rgba(123, 140, 255, 0.2);\n"
"  border-top: 3px solid var(--accent-2);\n"
"  border-radius: 50%;\n"
"  animation: spin 1s linear infinite;\n"
"  margin-bottom: 12px;\n"
"}\n"
"@keyframes spin { to { transform: rotate(360deg); } }\n"
"\n"
".btn-bar {\n"
"  display: flex;\n"
"  gap: 6px;\n"
"  padding: 10px;\n"
"  background: linear-gradient(180deg, rgba(20, 29, 51, 0.95), rgba(14, 21, 38, 0.95));\n"
"  border-top: 1px solid var(--line);\n"
"  flex-wrap: wrap;\n"
"  justify-content: center;\n"
"}\n"
".btn-bar button {\n"
"  padding: 7px 12px;\n"
"  font-size: 12px;\n"
"  background: linear-gradient(180deg, rgba(123, 140, 255, 0.22), rgba(90, 105, 214, 0.18));\n"
"  color: var(--text);\n"
"  border: 1px solid rgba(123, 140, 255, 0.35);\n"
"  border-radius: 10px;\n"
"  cursor: pointer;\n"
"  font-weight: 600;\n"
"  transition: transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease;\n"
"}\n"
".btn-bar button:hover {\n"
"  border-color: rgba(123, 140, 255, 0.65);\n"
"  box-shadow: 0 0 0 2px rgba(123, 140, 255, 0.18);\n"
"  transform: translateY(-1px);\n"
"}\n"
".btn-bar button:active { transform: translateY(0); }\n"
"\n"
"#remote-status {\n"
"  padding: 7px 10px;\n"
"  font-size: 11px;\n"
"  color: var(--text-dim);\n"
"  background: rgba(8, 12, 24, 0.88);\n"
"  text-align: center;\n"
"  border-top: 1px solid var(--line);\n"
"  letter-spacing: 0.02em;\n"
"}\n"
"\n"
"/* Right panel: AI */\n"
"#panel-ai {\n"
"  flex: 1;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  min-width: 0;\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 16px;\n"
"  overflow: hidden;\n"
"  background: var(--card);\n"
"  backdrop-filter: blur(12px);\n"
"  box-shadow: 0 14px 40px rgba(0, 0, 0, 0.45);\n"
"}\n"
"#panel-ai header {\n"
"  background: linear-gradient(135deg, rgba(22, 30, 54, 0.95), rgba(18, 27, 49, 0.95));\n"
"  padding: 12px 16px;\n"
"  border-bottom: 1px solid var(--line);\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: space-between;\n"
"}\n"
"#panel-ai header h1 {\n"
"  font-size: 15px;\n"
"  font-weight: 700;\n"
"  color: var(--text);\n"
"  letter-spacing: 0.01em;\n"
"}\n"
"#panel-ai header .status {\n"
"  font-size: 11px;\n"
"  color: var(--text-dim);\n"
"  background: rgba(123, 140, 255, 0.15);\n"
"  border: 1px solid rgba(123, 140, 255, 0.28);\n"
"  border-radius: 999px;\n"
"  padding: 4px 10px;\n"
"}\n"
".ai-container { flex: 1; display: flex; flex-direction: column; overflow: hidden; }\n"
"\n"
"/* Tabs */\n"
".tab-bar {\n"
"  display: grid;\n"
"  grid-template-columns: repeat(3, minmax(0, 1fr));\n"
"  gap: 6px;\n"
"  padding: 8px 10px;\n"
"  border-bottom: 1px solid var(--line);\n"
"  background: rgba(11, 16, 31, 0.7);\n"
"}\n"
".tab-btn {\n"
"  padding: 9px;\n"
"  text-align: center;\n"
"  font-size: 12px;\n"
"  font-weight: 700;\n"
"  cursor: pointer;\n"
"  border: 1px solid transparent;\n"
"  background: rgba(255, 255, 255, 0.02);\n"
"  color: var(--text-dim);\n"
"  border-radius: 10px;\n"
"  transition: all 0.18s ease;\n"
"}\n"
".tab-btn:hover {\n"
"  color: var(--text);\n"
"  border-color: rgba(123, 140, 255, 0.3);\n"
"  background: rgba(123, 140, 255, 0.08);\n"
"}\n"
".tab-btn.active {\n"
"  color: #f4f7ff;\n"
"  border-color: rgba(123, 140, 255, 0.7);\n"
"  background: linear-gradient(145deg, rgba(123, 140, 255, 0.35), rgba(54, 213, 255, 0.18));\n"
"}\n"
".tab-content { flex: 1; display: none; flex-direction: column; overflow: hidden; padding: 10px; gap: 10px; }\n"
".tab-content.active { display: flex; }\n"
"\n"
"/* Common */\n"
".panel {\n"
"  background: var(--card-soft);\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 12px;\n"
"}\n"
".panel-header {\n"
"  padding: 9px 12px;\n"
"  border-bottom: 1px solid var(--line);\n"
"  font-weight: 700;\n"
"  font-size: 12px;\n"
"  cursor: pointer;\n"
"  user-select: none;\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"}\n"
".panel-header:hover { background: rgba(123, 140, 255, 0.08); }\n"
".panel-body { padding: 10px; }\n"
".panel-body.collapsed { display: none; }\n"
"button {\n"
"  background: linear-gradient(150deg, #7b8cff, #5e72ff);\n"
"  color: #fff;\n"
"  border: 1px solid rgba(132, 147, 255, 0.65);\n"
"  padding: 8px 14px;\n"
"  border-radius: 10px;\n"
"  cursor: pointer;\n"
"  font-size: 12px;\n"
"  font-weight: 700;\n"
"  transition: transform 0.15s ease, box-shadow 0.15s ease, filter 0.15s ease;\n"
"}\n"
"button:hover {\n"
"  transform: translateY(-1px);\n"
"  box-shadow: 0 8px 20px rgba(69, 92, 255, 0.35);\n"
"}\n"
"button:disabled {\n"
"  background: rgba(120, 130, 160, 0.25);\n"
"  border-color: rgba(120, 130, 160, 0.25);\n"
"  color: #9ba5bf;\n"
"  cursor: not-allowed;\n"
"  box-shadow: none;\n"
"  transform: none;\n"
"}\n"
"button.secondary {\n"
"  background: rgba(115, 136, 198, 0.18);\n"
"  border-color: rgba(115, 136, 198, 0.45);\n"
"}\n"
"button.secondary:hover { box-shadow: 0 8px 18px rgba(90, 110, 180, 0.25); }\n"
"button.danger {\n"
"  background: linear-gradient(150deg, #ff6f8e, #ff4f74);\n"
"  border-color: rgba(255, 128, 154, 0.65);\n"
"}\n"
"button.success {\n"
"  background: linear-gradient(150deg, #35d39f, #20b784);\n"
"  border-color: rgba(89, 231, 178, 0.6);\n"
"}\n"
"select {\n"
"  background: rgba(10, 17, 33, 0.95);\n"
"  border: 1px solid rgba(123, 140, 255, 0.3);\n"
"  color: var(--text);\n"
"  padding: 7px 9px;\n"
"  border-radius: 9px;\n"
"  font-size: 12px;\n"
"  outline: none;\n"
"}\n"
"\n"
"/* Chat tab */\n"
"#chat-area {\n"
"  flex: 1;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  min-height: 0;\n"
"  background: rgba(8, 13, 26, 0.55);\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 12px;\n"
"  padding: 10px;\n"
"}\n"
"#chat-history { flex: 1; overflow-y: auto; margin-bottom: 10px; padding-right: 4px; }\n"
".msg {\n"
"  margin-bottom: 8px;\n"
"  padding: 9px 10px;\n"
"  border-radius: 10px;\n"
"  font-size: 12px;\n"
"  line-height: 1.55;\n"
"  white-space: pre-wrap;\n"
"  word-break: break-word;\n"
"  border: 1px solid transparent;\n"
"}\n"
".msg-user {\n"
"  background: rgba(74, 193, 255, 0.12);\n"
"  border-color: rgba(74, 193, 255, 0.32);\n"
"}\n"
".msg-assistant {\n"
"  background: rgba(79, 255, 176, 0.1);\n"
"  border-color: rgba(79, 255, 176, 0.28);\n"
"}\n"
".msg-tool {\n"
"  background: rgba(255, 200, 74, 0.12);\n"
"  border-color: rgba(255, 200, 74, 0.35);\n"
"  font-size: 11px;\n"
"}\n"
".msg-role {\n"
"  font-weight: 700;\n"
"  font-size: 10px;\n"
"  text-transform: uppercase;\n"
"  margin-bottom: 4px;\n"
"  letter-spacing: 0.04em;\n"
"}\n"
".msg-user .msg-role { color: #7ed2ff; }\n"
".msg-assistant .msg-role { color: #7cffbe; }\n"
".msg-tool .msg-role { color: #ffd989; }\n"
"#prompt-row { display: flex; gap: 8px; }\n"
"#prompt-input {\n"
"  flex: 1;\n"
"  background: rgba(8, 14, 28, 0.95);\n"
"  border: 1px solid rgba(123, 140, 255, 0.25);\n"
"  color: var(--text);\n"
"  padding: 9px;\n"
"  border-radius: 10px;\n"
"  font-size: 13px;\n"
"  outline: none;\n"
"  resize: none;\n"
"  line-height: 1.45;\n"
"}\n"
"#prompt-input:focus {\n"
"  border-color: rgba(54, 213, 255, 0.8);\n"
"  box-shadow: 0 0 0 3px rgba(54, 213, 255, 0.18);\n"
"}\n"
".chat-buttons { display: flex; gap: 6px; }\n"
"\n"
"/* Learn tab */\n"
"#rules-textarea {\n"
"  width: 100%;\n"
"  flex: 1;\n"
"  min-height: 170px;\n"
"  background: rgba(8, 14, 28, 0.95);\n"
"  border: 1px solid rgba(123, 140, 255, 0.25);\n"
"  color: var(--text);\n"
"  padding: 11px;\n"
"  border-radius: 10px;\n"
"  font-size: 12px;\n"
"  font-family: 'SF Mono', 'Consolas', 'Monaco', monospace;\n"
"  outline: none;\n"
"  resize: vertical;\n"
"  line-height: 1.65;\n"
"}\n"
"#rules-textarea:focus {\n"
"  border-color: rgba(54, 213, 255, 0.8);\n"
"  box-shadow: 0 0 0 3px rgba(54, 213, 255, 0.16);\n"
"}\n"
".learn-buttons { display: flex; gap: 8px; margin-top: 9px; align-items: center; flex-wrap: wrap; }\n"
"#summarize-status { font-size: 11px; color: var(--text-dim); margin-left: 2px; }\n"
"\n"
"/* Auto tab */\n"
".auto-card {\n"
"  background: rgba(8, 13, 26, 0.55);\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 12px;\n"
"  padding: 14px;\n"
"  text-align: center;\n"
"  flex-shrink: 0;\n"
"}\n"
".auto-card h3 { margin-bottom: 10px; font-size: 14px; }\n"
".auto-controls {\n"
"  display: flex;\n"
"  gap: 8px;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  flex-wrap: wrap;\n"
"}\n"
".auto-info {\n"
"  display: flex;\n"
"  gap: 14px;\n"
"  margin-top: 12px;\n"
"  justify-content: center;\n"
"  font-size: 12px;\n"
"  flex-wrap: wrap;\n"
"}\n"
".auto-info .label { color: var(--text-dim); }\n"
".auto-info .value { color: var(--good); font-weight: 700; }\n"
".auto-info .value.stopped { color: var(--bad); }\n"
"\n"
"/* Auto log */\n"
".auto-log-card {\n"
"  flex: 1;\n"
"  min-height: 0;\n"
"  background: rgba(8, 13, 26, 0.55);\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 12px;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"}\n"
".auto-log-header {\n"
"  padding: 8px 12px;\n"
"  border-bottom: 1px solid var(--line);\n"
"  font-weight: 700;\n"
"  font-size: 12px;\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"  flex-shrink: 0;\n"
"}\n"
".auto-log-header button { padding: 4px 9px; font-size: 10px; }\n"
"#auto-log-list { flex: 1; overflow-y: auto; padding: 8px 11px; }\n"
".log-entry {\n"
"  padding: 6px 0;\n"
"  border-bottom: 1px dashed rgba(120, 148, 215, 0.2);\n"
"  font-size: 11px;\n"
"  line-height: 1.55;\n"
"  font-family: 'SF Mono', 'Consolas', 'Monaco', monospace;\n"
"}\n"
".log-entry:last-child { border-bottom: none; }\n"
".log-ts { color: #7485b0; }\n"
".log-ai { color: var(--good); }\n"
".log-ai-text { color: #d4dcf2; }\n"
".log-tool { color: var(--warn); }\n"
".log-tool-detail { color: #b8c4e6; }\n"
"\n"
"/* Settings */\n"
".setting-row { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }\n"
".setting-row label { min-width: 70px; font-size: 12px; color: var(--text-dim); }\n"
".setting-row input {\n"
"  flex: 1;\n"
"  background: rgba(8, 14, 28, 0.95);\n"
"  border: 1px solid rgba(123, 140, 255, 0.26);\n"
"  color: var(--text);\n"
"  padding: 7px 9px;\n"
"  border-radius: 9px;\n"
"  font-size: 12px;\n"
"  outline: none;\n"
"}\n"
".setting-row input:focus {\n"
"  border-color: rgba(54, 213, 255, 0.8);\n"
"  box-shadow: 0 0 0 3px rgba(54, 213, 255, 0.14);\n"
"}\n"
"\n"
"::-webkit-scrollbar { width: 8px; }\n"
"::-webkit-scrollbar-track { background: transparent; }\n"
"::-webkit-scrollbar-thumb {\n"
"  background: linear-gradient(180deg, rgba(123, 140, 255, 0.65), rgba(54, 213, 255, 0.55));\n"
"  border-radius: 999px;\n"
"}\n"
"\n"
"@media (max-width: 1200px) {\n"
"  body { gap: 8px; padding: 8px; }\n"
"}\n"
"@media (max-width: 960px) {\n"
"  body { flex-direction: column; height: auto; min-height: 100vh; }\n"
"  #panel-remote, #panel-ai { min-height: 360px; }\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<!-- Left Panel: Remote -->\n"
"<div id=\"panel-remote\">\n"
"  <div id=\"video-wrapper\">\n"
"    <video id=\"remote-video\" autoplay muted playsinline></video>\n"
"    <canvas id=\"touch-overlay\"></canvas>\n"
"    <div id=\"video-loading\">\n"
"      <div class=\"spinner\"></div>\n"
"      <div>Loading video stream...</div>\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"btn-bar\">\n"
"    <button onclick=\"sendKey('back')\">Back</button>\n"
"    <button onclick=\"sendKey('home')\">Home</button>\n"
"    <button onclick=\"sendKey('app_switch')\">Recents</button>\n"
"    <button onclick=\"sendKey('volume_up')\">Vol+</button>\n"
"    <button onclick=\"sendKey('volume_down')\">Vol-</button>\n"
"    <button onclick=\"sendKey('power')\">Power</button>\n"
"  </div>\n"
"  <div id=\"remote-status\">Not connected</div>\n"
"</div>\n"
"\n"
"<!-- Right Panel: AI -->\n"
"<div id=\"panel-ai\">\n"
"  <header>\n"
"    <h1>SCRCPY AI CONTROLLER</h1>\n"
"    <span class=\"status\" id=\"status\">Connecting...</span>\n"
"  </header>\n"
"  <div class=\"ai-container\">\n"
"    <!-- Tab Bar -->\n"
"    <div class=\"tab-bar\">\n"
"      <button class=\"tab-btn active\" onclick=\"switchTab('chat')\">Chat</button>\n"
"      <button class=\"tab-btn\" onclick=\"switchTab('learn')\">Learn</button>\n"
"      <button class=\"tab-btn\" onclick=\"switchTab('auto')\">Auto</button>\n"
"    </div>\n"
"\n"
"    <!-- Chat Tab -->\n"
"    <div class=\"tab-content active\" id=\"tab-chat\">\n"
"      <div id=\"chat-area\">\n"
"        <div id=\"chat-history\"></div>\n"
"        <div id=\"prompt-row\">\n"
"          <textarea id=\"prompt-input\" rows=\"2\" placeholder=\"Enter prompt...\"\n"
"            onkeydown=\"if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();sendPrompt()}\"></textarea>\n"
"          <div class=\"chat-buttons\">\n"
"            <button onclick=\"sendPrompt()\">Send</button>\n"
"            <button class=\"secondary\" onclick=\"clearHistory()\">Clear</button>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Learn Tab -->\n"
"    <div class=\"tab-content\" id=\"tab-learn\">\n"
"      <h3 style=\"margin-bottom:6px;font-size:14px\">Game Rules</h3>\n"
"      <p style=\"font-size:11px;color:#888;margin-bottom:10px\">"
"Edit the game rules below. The AI will follow these rules during auto-play.</p>\n"
"      <textarea id=\"rules-textarea\" placeholder=\"Enter game rules here...\\n\\n"
"Example:\\n- Tap matching tiles to clear them\\n- Prioritize combos\\n- Avoid hitting bombs\"></textarea>\n"
"      <div class=\"learn-buttons\">\n"
"        <button class=\"secondary\" onclick=\"summarizeRules()\">Summarize from Chat</button>\n"
"        <button class=\"success\" onclick=\"saveRules()\">Save</button>\n"
"        <span id=\"summarize-status\"></span>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Auto Tab -->\n"
"    <div class=\"tab-content\" id=\"tab-auto\">\n"
"      <div class=\"auto-card\">\n"
"        <h3>AI Auto-Play</h3>\n"
"        <div class=\"auto-controls\">\n"
"          <button id=\"auto-start-btn\" class=\"success\" onclick=\"startAuto()\">Start Auto-Play</button>\n"
"          <button id=\"auto-stop-btn\" class=\"danger\" onclick=\"stopAuto()\" disabled>Stop</button>\n"
"        </div>\n"
"        <div class=\"auto-info\">\n"
"          <span><span class=\"label\">Status: </span>"
"<span class=\"value stopped\" id=\"auto-status-text\">Stopped</span></span>\n"
"          <span><span class=\"label\">Rules: </span>"
"<span id=\"auto-rules-preview\" style=\"color:#ccc\">Not set</span></span>\n"
"        </div>\n"
"      </div>\n"
"      <!-- Activity Log -->\n"
"      <div class=\"auto-log-card\">\n"
"        <div class=\"auto-log-header\">\n"
"          <span>Activity Log</span>\n"
"          <button class=\"secondary\" onclick=\"clearAutoLog()\">Clear</button>\n"
"        </div>\n"
"        <div id=\"auto-log-list\"></div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Settings (collapsible, shown on all tabs) -->\n"
"    <div class=\"panel\" style=\"margin:0 10px 10px;flex-shrink:0\">\n"
"      <div class=\"panel-header\" onclick=\"togglePanel(this)\">\n"
"        <span>Settings</span><span class=\"arrow\">&#9654;</span>\n"
"      </div>\n"
"      <div class=\"panel-body collapsed\">\n"
"        <div class=\"setting-row\">\n"
"          <label>API Key</label>\n"
"          <input id=\"cfg-api-key\" type=\"password\" placeholder=\"sk-...\">\n"
"        </div>\n"
"        <div class=\"setting-row\">\n"
"          <label>Game Model</label>\n"
"          <input id=\"cfg-model\" placeholder=\"qwen/qwen3.5-27b\">\n"
"        </div>\n"
"        <div class=\"setting-row\">\n"
"          <label>Vision Model</label>\n"
"          <input id=\"cfg-vision-model\" placeholder=\"google/gemini-2.0-flash-001\">\n"
"        </div>\n"
"        <div class=\"setting-row\">\n"
"          <label>Base URL</label>\n"
"          <input id=\"cfg-base-url\" placeholder=\"https://openrouter.ai/api/v1\">\n"
"        </div>\n"
"        <button onclick=\"applySettings()\" style=\"margin-top:4px\">Apply</button>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<script src=\"https://cdn.jsdelivr.net/npm/jmuxer@2.1.0/dist/jmuxer.min.js\"></script>\n"
"<script>\n"
"/* =================== AI Panel Logic (existing) =================== */\n"
"let lastMsgCount = 0;\n"
"let pollTimer = null;\n"
"let currentTab = 'chat';\n"
"let autoLogMsgIndex = 0;\n"
"\n"
"function switchTab(tab) {\n"
"  currentTab = tab;\n"
"  document.querySelectorAll('.tab-btn').forEach((btn, i) => {\n"
"    const tabs = ['chat', 'learn', 'auto'];\n"
"    btn.classList.toggle('active', tabs[i] === tab);\n"
"  });\n"
"  document.querySelectorAll('.tab-content').forEach(el => {\n"
"    el.classList.toggle('active', el.id === 'tab-' + tab);\n"
"  });\n"
"}\n"
"\n"
"function togglePanel(header) {\n"
"  const body = header.nextElementSibling;\n"
"  body.classList.toggle('collapsed');\n"
"  const arrow = header.querySelector('.arrow');\n"
"  if (arrow) arrow.textContent = body.classList.contains('collapsed') ? '\\u25B6' : '\\u25BC';\n"
"}\n"
"\n"
"async function api(method, path, body) {\n"
"  try {\n"
"    const opts = { method };\n"
"    if (body !== undefined) {\n"
"      opts.headers = {'Content-Type': 'application/json'};\n"
"      opts.body = JSON.stringify(body);\n"
"    }\n"
"    const r = await fetch(path, opts);\n"
"    if (!r.ok) throw new Error(r.statusText);\n"
"    return await r.json();\n"
"  } catch(e) {\n"
"    console.error('API error:', e);\n"
"    return null;\n"
"  }\n"
"}\n"
"\n"
"function escapeHtml(s) {\n"
"  const d = document.createElement('div');\n"
"  d.textContent = s;\n"
"  return d.innerHTML;\n"
"}\n"
"\n"
"function fmtTime() {\n"
"  const d = new Date();\n"
"  const pad = n => String(n).padStart(2,'0');\n"
"  return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())\n"
"    +' '+pad(d.getHours())+':'+pad(d.getMinutes())+':'+pad(d.getSeconds());\n"
"}\n"
"\n"
"function formatToolCall(tc) {\n"
"  try {\n"
"    const fn = tc.function ? tc.function.name : '';\n"
"    const raw = tc.function ? tc.function.arguments : '{}';\n"
"    const a = JSON.parse(raw);\n"
"    if (fn === 'position_click') return 'click ['+a.x+','+a.y+']';\n"
"    if (fn === 'position_long_press') return 'long_press ['+a.x+','+a.y+'] '+(a.duration_ms||500)+'ms';\n"
"    if (fn === 'swipe') return 'swipe ['+a.x1+','+a.y1+'\\u2192'+a.x2+','+a.y2+']';\n"
"    if (fn === 'key_press') return 'key ['+a.keycode+']';\n"
"    if (fn === 'key_down') return 'key_down ['+a.keycode+']';\n"
"    if (fn === 'key_up') return 'key_up ['+a.keycode+']';\n"
"    if (fn === 'input_text') return 'text \\\"'+(a.text||'').substring(0,30)+'\\\"';\n"
"    if (fn === 'screenshot') return 'screenshot';\n"
"    return fn+'('+raw.substring(0,40)+')';\n"
"  } catch(e) { return '(parse error)'; }\n"
"}\n"
"\n"
"function appendAutoLog(messages) {\n"
"  if (!messages || messages.length <= autoLogMsgIndex) return;\n"
"  const logEl = document.getElementById('auto-log-list');\n"
"  const wasAtBottom = logEl.scrollTop + logEl.clientHeight >= logEl.scrollHeight - 20;\n"
"  const ts = fmtTime();\n"
"\n"
"  for (let i = autoLogMsgIndex; i < messages.length; i++) {\n"
"    const m = messages[i];\n"
"    if (m.role === 'system') continue;\n"
"\n"
"    if (m.role === 'assistant') {\n"
"      let hasContent = m.content && m.content.trim();\n"
"      let hasTc = false;\n"
"      let tcParts = [];\n"
"      if (m.tool_calls) {\n"
"        try {\n"
"          const tcs = JSON.parse(m.tool_calls);\n"
"          if (Array.isArray(tcs) && tcs.length > 0) {\n"
"            hasTc = true;\n"
"            tcParts = tcs.map(formatToolCall);\n"
"          }\n"
"        } catch(e) {}\n"
"      }\n"
"      if (!hasContent && !hasTc) continue;\n"
"      const div = document.createElement('div');\n"
"      div.className = 'log-entry';\n"
"      let html = '';\n"
"      if (hasContent) {\n"
"        const text = m.content.length > 120 ? m.content.substring(0,120)+'...' : m.content;\n"
"        html += '<span class=\"log-ts\">['+escapeHtml(ts)+']</span> ';\n"
"        html += '<span class=\"log-ai\">AI:</span> ';\n"
"        html += '<span class=\"log-ai-text\">\\\"'+escapeHtml(text)+'\\\"</span>';\n"
"      }\n"
"      if (hasTc) {\n"
"        if (hasContent) html += '<br>';\n"
"        html += '<span class=\"log-ts\">['+escapeHtml(ts)+']</span> ';\n"
"        html += '<span class=\"log-tool\">Tool:</span> ';\n"
"        html += '<span class=\"log-tool-detail\">'+escapeHtml(tcParts.join(' | '))+'</span>';\n"
"      }\n"
"      div.innerHTML = html;\n"
"      logEl.appendChild(div);\n"
"    } else if (m.role === 'tool') {\n"
"      const div = document.createElement('div');\n"
"      div.className = 'log-entry';\n"
"      const text = (m.content||'').length > 100 ? m.content.substring(0,100)+'...' : (m.content||'');\n"
"      div.innerHTML = '<span class=\"log-ts\">['+escapeHtml(ts)+']</span> '\n"
"        + '<span class=\"log-tool\">Result:</span> '\n"
"        + '<span class=\"log-tool-detail\">'+escapeHtml(text)+'</span>';\n"
"      logEl.appendChild(div);\n"
"    }\n"
"  }\n"
"  autoLogMsgIndex = messages.length;\n"
"  if (wasAtBottom) logEl.scrollTop = logEl.scrollHeight;\n"
"}\n"
"\n"
"function clearAutoLog() {\n"
"  document.getElementById('auto-log-list').innerHTML = '';\n"
"}\n"
"\n"
"function renderMessages(messages) {\n"
"  const el = document.getElementById('chat-history');\n"
"  const atBottom = el.scrollTop + el.clientHeight >= el.scrollHeight - 30;\n"
"  el.innerHTML = '';\n"
"  for (const m of messages) {\n"
"    if (m.role === 'system') continue;\n"
"    let cls = 'msg-' + m.role;\n"
"    let role = m.role === 'user' ? 'You' : m.role === 'assistant' ? 'AI' : (m.name || 'tool');\n"
"    const div = document.createElement('div');\n"
"    div.className = 'msg ' + cls;\n"
"    div.innerHTML = '<div class=\"msg-role\">' + escapeHtml(role) + '</div>' + escapeHtml(m.content || '');\n"
"    el.appendChild(div);\n"
"  }\n"
"  if (atBottom || messages.length !== lastMsgCount) {\n"
"    el.scrollTop = el.scrollHeight;\n"
"    lastMsgCount = messages.length;\n"
"  }\n"
"}\n"
"\n"
"function renderAutoState(autoRunning, gameRules) {\n"
"  const statusEl = document.getElementById('auto-status-text');\n"
"  const startBtn = document.getElementById('auto-start-btn');\n"
"  const stopBtn = document.getElementById('auto-stop-btn');\n"
"  const previewEl = document.getElementById('auto-rules-preview');\n"
"  if (autoRunning) {\n"
"    statusEl.textContent = 'Running';\n"
"    statusEl.className = 'value';\n"
"    startBtn.disabled = true;\n"
"    stopBtn.disabled = false;\n"
"  } else {\n"
"    statusEl.textContent = 'Stopped';\n"
"    statusEl.className = 'value stopped';\n"
"    startBtn.disabled = false;\n"
"    stopBtn.disabled = true;\n"
"  }\n"
"  if (gameRules && gameRules.trim()) {\n"
"    const preview = gameRules.length > 60 ? gameRules.substring(0, 60) + '...' : gameRules;\n"
"    previewEl.textContent = preview;\n"
"  } else {\n"
"    previewEl.textContent = 'Not set';\n"
"  }\n"
"}\n"
"\n"
"let rulesLoaded = false;\n"
"async function pollState() {\n"
"  const s = await api('GET', '/api/state');\n"
"  if (!s) {\n"
"    document.getElementById('status').textContent = 'Disconnected';\n"
"    return;\n"
"  }\n"
"  document.getElementById('status').textContent =\n"
"    'Connected | ' + (s.screen_width||0) + 'x' + (s.screen_height||0);\n"
"  renderMessages(s.messages || []);\n"
"  renderAutoState(s.auto_running, s.game_rules);\n"
"  appendAutoLog(s.messages || []);\n"
"  if (!rulesLoaded && s.game_rules) {\n"
"    document.getElementById('rules-textarea').value = s.game_rules;\n"
"    rulesLoaded = true;\n"
"  }\n"
"  const ak = document.getElementById('cfg-api-key');\n"
"  if (!ak.value && s.config_api_key) ak.value = s.config_api_key;\n"
"  const md = document.getElementById('cfg-model');\n"
"  if (!md.value && s.config_model) md.value = s.config_model;\n"
"  const vm = document.getElementById('cfg-vision-model');\n"
"  if (!vm.value && s.config_vision_model) vm.value = s.config_vision_model;\n"
"  const bu = document.getElementById('cfg-base-url');\n"
"  if (!bu.value && s.config_base_url) bu.value = s.config_base_url;\n"
"}\n"
"\n"
"async function sendPrompt() {\n"
"  const el = document.getElementById('prompt-input');\n"
"  const text = el.value.trim();\n"
"  if (!text) return;\n"
"  el.value = '';\n"
"  await api('POST', '/api/prompt', {prompt: text});\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function clearHistory() {\n"
"  await api('POST', '/api/clear');\n"
"  autoLogMsgIndex = 0;\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function saveRules() {\n"
"  const rules = document.getElementById('rules-textarea').value;\n"
"  await api('POST', '/api/game-rules', {rules: rules});\n"
"  document.getElementById('summarize-status').textContent = 'Saved!';\n"
"  setTimeout(() => { document.getElementById('summarize-status').textContent = ''; }, 2000);\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function summarizeRules() {\n"
"  const statusEl = document.getElementById('summarize-status');\n"
"  statusEl.textContent = 'Summarizing...';\n"
"  const result = await api('POST', '/api/game-rules/summarize');\n"
"  if (result && result.rules) {\n"
"    document.getElementById('rules-textarea').value = result.rules;\n"
"    statusEl.textContent = 'Done! Review and save.';\n"
"  } else {\n"
"    statusEl.textContent = 'Failed to summarize.';\n"
"  }\n"
"  setTimeout(() => { statusEl.textContent = ''; }, 3000);\n"
"}\n"
"\n"
"async function startAuto() {\n"
"  await api('POST', '/api/auto/start');\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function stopAuto() {\n"
"  await api('POST', '/api/auto/stop');\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function applySettings() {\n"
"  const api_key = document.getElementById('cfg-api-key').value;\n"
"  const model = document.getElementById('cfg-model').value;\n"
"  const vision_model = document.getElementById('cfg-vision-model').value;\n"
"  const base_url = document.getElementById('cfg-base-url').value;\n"
"  await api('POST', '/api/config', {api_key, model, vision_model, base_url});\n"
"}\n"
"\n"
"// Start polling\n"
"pollState();\n"
"pollTimer = setInterval(pollState, 2000);\n"
"\n"
"/* =================== Remote Panel Logic =================== */\n"
"let deviceWidth = 0, deviceHeight = 0;\n"
"let deviceCodec = null;\n"
"let jmuxerInstance = null;\n"
"let videoWs = null;\n"
"let controlWs = null;\n"
"let videoStarted = false;\n"
"let videoRotationDeg = 0;\n"
"var isChromeBrowser = /Chrome\\//.test(navigator.userAgent) && !/Edg\\//.test(navigator.userAgent);\n"
"\n"
"function updateVideoOrientation() {\n"
"  if (!isChromeBrowser) return;\n"
"  var video = document.getElementById('remote-video');\n"
"  var vw = video.videoWidth, vh = video.videoHeight;\n"
"  if (!vw || !vh || !deviceWidth || !deviceHeight) return;\n"
"  var needsRotation = (deviceHeight > deviceWidth) !== (vh > vw);\n"
"  var newDeg = needsRotation ? -90 : 0;\n"
"  if (newDeg === videoRotationDeg) return;\n"
"  videoRotationDeg = newDeg;\n"
"  applyVideoLayout();\n"
"}\n"
"\n"
"function applyVideoLayout() {\n"
"  var video = document.getElementById('remote-video');\n"
"  if (videoRotationDeg === 0) {\n"
"    video.classList.remove('rotated');\n"
"    video.style.transform = '';\n"
"    video.style.width = '';\n"
"    video.style.height = '';\n"
"    return;\n"
"  }\n"
"  var wrapper = document.getElementById('video-wrapper');\n"
"  var wW = wrapper.clientWidth, wH = wrapper.clientHeight;\n"
"  var ar = deviceWidth / deviceHeight;\n"
"  var visW, visH;\n"
"  if (ar < wW / wH) { visH = wH; visW = visH * ar; }\n"
"  else { visW = wW; visH = visW / ar; }\n"
"  video.classList.add('rotated');\n"
"  video.style.width = visH + 'px';\n"
"  video.style.height = visW + 'px';\n"
"  video.style.transform = 'translate(-50%, -50%) rotate(-90deg)';\n"
"}\n"
"\n"
"function initVideoWs() {\n"
"  const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"  const url = proto + '//' + location.host + '/ws/video';\n"
"  videoWs = new WebSocket(url);\n"
"  videoWs.binaryType = 'arraybuffer';\n"
"\n"
"  videoWs.onopen = () => {\n"
"    document.getElementById('remote-status').textContent = 'Video: Connected';\n"
"    videoStarted = false;\n"
"    document.getElementById('video-loading').style.display = 'flex';\n"
"  };\n"
"\n"
"  videoWs.onmessage = (evt) => {\n"
"    if (typeof evt.data === 'string') {\n"
"      try {\n"
"        const info = JSON.parse(evt.data);\n"
"        deviceWidth = info.width || 0;\n"
"        deviceHeight = info.height || 0;\n"
"        const newCodec = info.codec || 'h264';\n"
"        console.log('Video info: ' + deviceWidth + 'x' + deviceHeight + ' codec:' + newCodec);\n"
"        document.getElementById('remote-status').textContent =\n"
"          'Video: ' + deviceWidth + 'x' + deviceHeight + ' [' + newCodec.toUpperCase() + ']';\n"
"        videoRotationDeg = 0;\n"
"        resizeOverlay();\n"
"        // Initialize or reinitialize jmuxer when codec is first known or changes\n"
"        if (!jmuxerInstance || newCodec !== deviceCodec) {\n"
"          deviceCodec = newCodec;\n"
"          initJmuxer(newCodec);\n"
"        }\n"
"      } catch(e) {}\n"
"      return;\n"
"    }\n"
"    // Binary video data (H.264 or H.265) — already Annex-B from server\n"
"    if (jmuxerInstance) {\n"
"      var data = new Uint8Array(evt.data);\n"
"      frameCount++;\n"
"      try {\n"
"        jmuxerInstance.feed({ video: data });\n"
"      } catch(e) {\n"
"        console.error('jmuxer feed error:', e, 'frame:', frameCount, 'size:', data.length);\n"
"      }\n"
"      // Sync playback position to live edge\n"
"      var vid = document.getElementById('remote-video');\n"
"      if (vid.buffered.length > 0) {\n"
"        var end = vid.buffered.end(vid.buffered.length - 1);\n"
"        if (end - vid.currentTime > 0.5) {\n"
"          vid.currentTime = end - 0.1;\n"
"        }\n"
"        if (vid.paused) vid.play().catch(function(){});\n"
"      }\n"
"      if (frameCount % 30 === 0) {\n"
"        var vEl = document.getElementById('remote-video');\n"
"        document.getElementById('remote-status').textContent =\n"
"          'Dev:' + deviceWidth + 'x' + deviceHeight\n"
"          + ' Vid:' + (vEl.videoWidth||'?') + 'x' + (vEl.videoHeight||'?')\n"
"          + ' rot:' + videoRotationDeg\n"
"          + ' [' + (deviceCodec||'h264').toUpperCase() + '] F:' + frameCount;\n"
"      }\n"
"    }\n"
"  };\n"
"\n"
"  videoWs.onclose = () => {\n"
"    document.getElementById('remote-status').textContent = 'Video: Disconnected';\n"
"    setTimeout(initVideoWs, 3000);\n"
"  };\n"
"\n"
"  videoWs.onerror = () => {\n"
"    videoWs.close();\n"
"  };\n"
"}\n"
"\n"
"function initControlWs() {\n"
"  const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"  const url = proto + '//' + location.host + '/ws/control';\n"
"  controlWs = new WebSocket(url);\n"
"\n"
"  controlWs.onclose = () => {\n"
"    setTimeout(initControlWs, 3000);\n"
"  };\n"
"\n"
"  controlWs.onerror = () => {\n"
"    controlWs.close();\n"
"  };\n"
"}\n"
"\n"
"function sendKey(key) {\n"
"  if (controlWs && controlWs.readyState === WebSocket.OPEN) {\n"
"    controlWs.send(JSON.stringify({type:'key', key: key}));\n"
"  }\n"
"}\n"
"\n"
"function sendTouch(action, clientX, clientY) {\n"
"  var dbg = document.getElementById('remote-status');\n"
"  if (!controlWs || controlWs.readyState !== WebSocket.OPEN) {\n"
"    dbg.textContent = 'Touch: WS not open';\n"
"    return;\n"
"  }\n"
"\n"
"  const video = document.getElementById('remote-video');\n"
"  // When Chrome rotation fix is active, use device dims; otherwise use video dims\n"
"  const vw = (videoRotationDeg !== 0) ? deviceWidth : (video.videoWidth || deviceWidth);\n"
"  const vh = (videoRotationDeg !== 0) ? deviceHeight : (video.videoHeight || deviceHeight);\n"
"  if (!vw || !vh) {\n"
"    dbg.textContent = 'Touch: no dimensions';\n"
"    return;\n"
"  }\n"
"\n"
"  const wrapper = document.getElementById('video-wrapper');\n"
"  const wrapperRect = wrapper.getBoundingClientRect();\n"
"  const wW = wrapperRect.width;\n"
"  const wH = wrapperRect.height;\n"
"\n"
"  let renderW, renderH;\n"
"  if (vw / vh > wW / wH) {\n"
"    renderW = wW;\n"
"    renderH = wW * vh / vw;\n"
"  } else {\n"
"    renderH = wH;\n"
"    renderW = wH * vw / vh;\n"
"  }\n"
"\n"
"  const offsetX = (wW - renderW) / 2;\n"
"  const offsetY = (wH - renderH) / 2;\n"
"\n"
"  const relX = clientX - wrapperRect.left - offsetX;\n"
"  const relY = clientY - wrapperRect.top - offsetY;\n"
"\n"
"  const normX = Math.max(0, Math.min(1, relX / renderW));\n"
"  const normY = Math.max(0, Math.min(1, relY / renderH));\n"
"\n"
"  const x = Math.round(normX * vw);\n"
"  const y = Math.round(normY * vh);\n"
"\n"
"  var msg = {type:'touch', action:action, x:x, y:y, w:vw, h:vh};\n"
"  controlWs.send(JSON.stringify(msg));\n"
"  dbg.textContent = 'Touch: ' + action + ' ' + x + ',' + y + ' (' + vw + 'x' + vh + ')';\n"
"}\n"
"\n"
"function resizeOverlay() {\n"
"  const canvas = document.getElementById('touch-overlay');\n"
"  const wrapper = document.getElementById('video-wrapper');\n"
"  canvas.width = wrapper.clientWidth;\n"
"  canvas.height = wrapper.clientHeight;\n"
"}\n"
"\n"
"// Touch/mouse events on canvas overlay\n"
"(function() {\n"
"  const overlay = document.getElementById('touch-overlay');\n"
"  let isDown = false;\n"
"\n"
"  // Mouse events\n"
"  overlay.addEventListener('mousedown', (e) => {\n"
"    e.preventDefault();\n"
"    isDown = true;\n"
"    console.log('mousedown', e.clientX, e.clientY);\n"
"    sendTouch('down', e.clientX, e.clientY);\n"
"  });\n"
"  overlay.addEventListener('mousemove', (e) => {\n"
"    if (!isDown) return;\n"
"    e.preventDefault();\n"
"    sendTouch('move', e.clientX, e.clientY);\n"
"  });\n"
"  overlay.addEventListener('mouseup', (e) => {\n"
"    if (!isDown) return;\n"
"    isDown = false;\n"
"    e.preventDefault();\n"
"    sendTouch('up', e.clientX, e.clientY);\n"
"  });\n"
"  overlay.addEventListener('mouseleave', (e) => {\n"
"    if (!isDown) return;\n"
"    isDown = false;\n"
"    sendTouch('up', e.clientX, e.clientY);\n"
"  });\n"
"\n"
"  // Touch events\n"
"  overlay.addEventListener('touchstart', (e) => {\n"
"    e.preventDefault();\n"
"    const t = e.touches[0];\n"
"    isDown = true;\n"
"    sendTouch('down', t.clientX, t.clientY);\n"
"  });\n"
"  overlay.addEventListener('touchmove', (e) => {\n"
"    e.preventDefault();\n"
"    const t = e.touches[0];\n"
"    sendTouch('move', t.clientX, t.clientY);\n"
"  });\n"
"  overlay.addEventListener('touchend', (e) => {\n"
"    e.preventDefault();\n"
"    isDown = false;\n"
"    const t = e.changedTouches[0];\n"
"    sendTouch('up', t.clientX, t.clientY);\n"
"  });\n"
"  overlay.addEventListener('touchcancel', (e) => {\n"
"    e.preventDefault();\n"
"    isDown = false;\n"
"    const t = e.changedTouches[0];\n"
"    sendTouch('up', t.clientX, t.clientY);\n"
"  });\n"
"\n"
"  window.addEventListener('resize', function() {\n"
"    resizeOverlay();\n"
"    if (videoRotationDeg !== 0) applyVideoLayout();\n"
"  });\n"
"})();\n"
"\n"
"let frameCount = 0;\n"
"\n"
"function initJmuxer(codec) {\n"
"  const statusEl = document.getElementById('remote-status');\n"
"  if (typeof JMuxer === 'undefined') {\n"
"    statusEl.textContent = 'Error: jmuxer.js not loaded';\n"
"    return;\n"
"  }\n"
"\n"
"  if (typeof MediaSource === 'undefined') {\n"
"    statusEl.textContent = 'Error: MediaSource API not supported';\n"
"    return;\n"
"  }\n"
"\n"
"  // Check MSE codec support based on server-reported codec\n"
"  var mseCodec;\n"
"  var jmuxerVideoCodec;\n"
"  if (codec === 'h265') {\n"
"    mseCodec = 'video/mp4; codecs=\\\"hev1.1.6.L93.B0\\\"';\n"
"    jmuxerVideoCodec = 'H265';\n"
"  } else {\n"
"    mseCodec = 'video/mp4; codecs=\\\"avc1.640028\\\"';\n"
"    jmuxerVideoCodec = undefined;\n"
"  }\n"
"\n"
"  if (!MediaSource.isTypeSupported(mseCodec)) {\n"
"    statusEl.textContent = 'Error: ' + codec.toUpperCase() + ' codec not supported by browser';\n"
"    console.error('MSE codec not supported:', mseCodec);\n"
"    return;\n"
"  }\n"
"\n"
"  // Destroy previous instance if codec changed\n"
"  if (jmuxerInstance) {\n"
"    try { jmuxerInstance.destroy(); } catch(e) {}\n"
"    jmuxerInstance = null;\n"
"  }\n"
"\n"
"  try {\n"
"    var opts = {\n"
"      node: 'remote-video',\n"
"      mode: 'video',\n"
"      flushingTime: 100,\n"
"      fps: 30,\n"
"      debug: true,\n"
"      onReady: function() {\n"
"        console.log('JMuxer ready (' + codec + ')');\n"
"        statusEl.textContent = 'JMuxer ready [' + codec.toUpperCase() + '], waiting for video...';\n"
"      },\n"
"      onError: function(err) {\n"
"        console.error('JMuxer error:', err);\n"
"        statusEl.textContent = 'JMuxer error: ' + (err.message || err);\n"
"      }\n"
"    };\n"
"    if (jmuxerVideoCodec) {\n"
"      opts.videoCodec = jmuxerVideoCodec;\n"
"    }\n"
"    jmuxerInstance = new JMuxer(opts);\n"
"    console.log('JMuxer initialized with codec:', codec, jmuxerVideoCodec || 'H264 (default)');\n"
"    statusEl.textContent = 'JMuxer initialized [' + codec.toUpperCase() + '], connecting...';\n"
"  } catch(e) {\n"
"    statusEl.textContent = 'JMuxer init error: ' + e.message;\n"
"    return;\n"
"  }\n"
"}\n"
"\n"
"// Initialize WebSockets (jmuxer is deferred until codec info received)\n"
"(function() {\n"
"  // Hide loading overlay only when video actually renders frames\n"
"  var remoteVid = document.getElementById('remote-video');\n"
"  remoteVid.addEventListener('timeupdate', function() {\n"
"    if (!videoStarted && remoteVid.currentTime > 0) {\n"
"      videoStarted = true;\n"
"      document.getElementById('video-loading').style.display = 'none';\n"
"      updateVideoOrientation();\n"
"    }\n"
"  });\n"
"  remoteVid.addEventListener('resize', function() {\n"
"    updateVideoOrientation();\n"
"  });\n"
"\n"
"  initVideoWs();\n"
"  initControlWs();\n"
"  resizeOverlay();\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif
