#ifndef SC_WEB_UI_H
#define SC_WEB_UI_H

static const char WEB_UI_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>scrcpy AI Control</title>\n"
"<style>\n"
"* { margin: 0; padding: 0; box-sizing: border-box; }\n"
"body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
"  background: #1a1a2e; color: #e0e0e0; height: 100vh; display: flex; margin: 0; }\n"
"\n"
"/* Left panel: Remote */\n"
"#panel-remote { flex: 1; display: flex; flex-direction: column;\n"
"  border-right: 1px solid #333; min-width: 0; }\n"
"#video-wrapper { flex: 1; display: flex; justify-content: center;\n"
"  align-items: center; background: #000; min-height: 0; position: relative; overflow: hidden; }\n"
"#remote-video { max-width: 100%; max-height: 100%; object-fit: contain; display: block; }\n"
"#touch-overlay { position: absolute; inset: 0; cursor: crosshair;\n"
"  touch-action: none; }\n"
"#video-loading { position: absolute; inset: 0; display: flex; flex-direction: column;\n"
"  justify-content: center; align-items: center; background: #000; color: #aaa;\n"
"  font-size: 14px; z-index: 10; pointer-events: none; }\n"
"#video-loading .spinner { width: 40px; height: 40px; border: 3px solid #333;\n"
"  border-top: 3px solid #e94560; border-radius: 50%; animation: spin 1s linear infinite;\n"
"  margin-bottom: 12px; }\n"
"@keyframes spin { to { transform: rotate(360deg); } }\n"
".btn-bar { display: flex; gap: 4px; padding: 6px 8px; background: #16213e;\n"
"  border-top: 1px solid #0f3460; flex-wrap: wrap; justify-content: center; }\n"
".btn-bar button { padding: 6px 12px; font-size: 12px; background: #0f3460;\n"
"  color: #e0e0e0; border: 1px solid #1a4a7a; border-radius: 4px;\n"
"  cursor: pointer; font-weight: 600; }\n"
".btn-bar button:hover { background: #1a4a7a; }\n"
".btn-bar button:active { background: #2a5a8a; }\n"
"#remote-status { padding: 4px 8px; font-size: 11px; color: #888;\n"
"  background: #111; text-align: center; }\n"
"\n"
"/* Right panel: AI */\n"
"#panel-ai { flex: 1; display: flex; flex-direction: column; min-width: 0; }\n"
"#panel-ai header { background: #16213e; padding: 10px 16px; border-bottom: 1px solid #0f3460;\n"
"  display: flex; align-items: center; justify-content: space-between; }\n"
"#panel-ai header h1 { font-size: 16px; color: #e94560; }\n"
"#panel-ai header .status { font-size: 11px; color: #888; }\n"
".ai-container { flex: 1; display: flex; flex-direction: column; overflow: hidden; }\n"
"\n"
"/* Tabs */\n"
".tab-bar { display: flex; background: #16213e; border-bottom: 2px solid #0f3460; }\n"
".tab-btn { flex: 1; padding: 8px; text-align: center; font-size: 13px; font-weight: 600;\n"
"  cursor: pointer; border: none; background: transparent; color: #888;\n"
"  border-bottom: 2px solid transparent; transition: all 0.2s; }\n"
".tab-btn:hover { color: #ccc; background: #1a2744; }\n"
".tab-btn.active { color: #e94560; border-bottom-color: #e94560; }\n"
".tab-content { flex: 1; display: none; flex-direction: column; overflow: hidden; padding: 10px; gap: 10px; }\n"
".tab-content.active { display: flex; }\n"
"\n"
"/* Common */\n"
".panel { background: #16213e; border: 1px solid #0f3460; border-radius: 8px; }\n"
".panel-header { padding: 8px 12px; border-bottom: 1px solid #0f3460; font-weight: 600;\n"
"  font-size: 13px; cursor: pointer; user-select: none; display: flex;\n"
"  justify-content: space-between; align-items: center; }\n"
".panel-header:hover { background: #1a2744; }\n"
".panel-body { padding: 10px; }\n"
".panel-body.collapsed { display: none; }\n"
"button { background: #e94560; color: #fff; border: none; padding: 7px 14px;\n"
"  border-radius: 6px; cursor: pointer; font-size: 12px; font-weight: 600; }\n"
"button:hover { background: #c73652; }\n"
"button:disabled { background: #555; cursor: not-allowed; }\n"
"button.secondary { background: #0f3460; }\n"
"button.secondary:hover { background: #1a4a7a; }\n"
"button.danger { background: #a03030; }\n"
"button.danger:hover { background: #c04040; }\n"
"button.success { background: #2a7a3a; }\n"
"button.success:hover { background: #3a9a4a; }\n"
"select { background: #0d1b2a; border: 1px solid #0f3460; color: #e0e0e0;\n"
"  padding: 5px 7px; border-radius: 6px; font-size: 12px; outline: none; }\n"
"\n"
"/* Chat tab */\n"
"#tab-chat { }\n"
"#chat-area { flex: 1; display: flex; flex-direction: column; min-height: 0; }\n"
"#chat-history { flex: 1; overflow-y: auto; margin-bottom: 8px; padding-right: 4px; }\n"
".msg { margin-bottom: 6px; padding: 6px 8px; border-radius: 6px; font-size: 12px;\n"
"  line-height: 1.5; white-space: pre-wrap; word-break: break-word; }\n"
".msg-user { background: #1a3a5c; border-left: 3px solid #4ac1ff; }\n"
".msg-assistant { background: #1a3c2e; border-left: 3px solid #4aff7a; }\n"
".msg-tool { background: #3c3a1a; border-left: 3px solid #ffc84a; font-size: 11px; }\n"
".msg-role { font-weight: 700; font-size: 10px; text-transform: uppercase; margin-bottom: 3px; }\n"
".msg-user .msg-role { color: #4ac1ff; }\n"
".msg-assistant .msg-role { color: #4aff7a; }\n"
".msg-tool .msg-role { color: #ffc84a; }\n"
"#prompt-row { display: flex; gap: 6px; }\n"
"#prompt-input { flex: 1; background: #0d1b2a; border: 1px solid #0f3460; color: #e0e0e0;\n"
"  padding: 8px; border-radius: 6px; font-size: 13px; outline: none; resize: none; }\n"
"#prompt-input:focus { border-color: #e94560; }\n"
".chat-buttons { display: flex; gap: 4px; }\n"
"\n"
"/* Learn tab */\n"
"#tab-learn { }\n"
"#rules-textarea { width: 100%; flex: 1; min-height: 150px; background: #0d1b2a;\n"
"  border: 1px solid #0f3460; color: #e0e0e0; padding: 10px; border-radius: 6px;\n"
"  font-size: 12px; font-family: monospace; outline: none; resize: vertical; line-height: 1.6; }\n"
"#rules-textarea:focus { border-color: #e94560; }\n"
".learn-buttons { display: flex; gap: 6px; margin-top: 8px; }\n"
"#summarize-status { font-size: 11px; color: #888; margin-left: 6px; line-height: 28px; }\n"
"\n"
"/* Auto tab */\n"
"#tab-auto { }\n"
".auto-card { background: #16213e; border: 1px solid #0f3460; border-radius: 8px;\n"
"  padding: 12px; text-align: center; flex-shrink: 0; }\n"
".auto-card h3 { margin-bottom: 10px; font-size: 14px; }\n"
".auto-controls { display: flex; gap: 8px; align-items: center; justify-content: center;\n"
"  flex-wrap: wrap; }\n"
".auto-info { display: flex; gap: 12px; margin-top: 10px; justify-content: center; font-size: 12px; }\n"
".auto-info .label { color: #888; }\n"
".auto-info .value { color: #4aff7a; font-weight: 600; }\n"
".auto-info .value.stopped { color: #e94560; }\n"
"\n"
"/* Auto log */\n"
".auto-log-card { flex: 1; min-height: 0; background: #16213e; border: 1px solid #0f3460;\n"
"  border-radius: 8px; display: flex; flex-direction: column; }\n"
".auto-log-header { padding: 6px 12px; border-bottom: 1px solid #0f3460;\n"
"  font-weight: 600; font-size: 12px; display: flex; justify-content: space-between;\n"
"  align-items: center; flex-shrink: 0; }\n"
".auto-log-header button { padding: 2px 8px; font-size: 10px; }\n"
"#auto-log-list { flex: 1; overflow-y: auto; padding: 6px 10px; }\n"
".log-entry { padding: 4px 0; border-bottom: 1px solid #0a1628; font-size: 11px;\n"
"  line-height: 1.5; font-family: 'SF Mono', 'Consolas', 'Monaco', monospace; }\n"
".log-entry:last-child { border-bottom: none; }\n"
".log-ts { color: #666; }\n"
".log-ai { color: #4aff7a; }\n"
".log-ai-text { color: #c0c0c0; }\n"
".log-tool { color: #ffc84a; }\n"
".log-tool-detail { color: #a0a0a0; }\n"
"\n"
"/* Settings */\n"
".setting-row { display: flex; align-items: center; gap: 6px; margin-bottom: 6px; }\n"
".setting-row label { min-width: 70px; font-size: 12px; color: #aaa; }\n"
".setting-row input { flex: 1; background: #0d1b2a; border: 1px solid #0f3460; color: #e0e0e0;\n"
"  padding: 6px; border-radius: 6px; font-size: 12px; outline: none; }\n"
"\n"
"::-webkit-scrollbar { width: 6px; }\n"
"::-webkit-scrollbar-track { background: transparent; }\n"
"::-webkit-scrollbar-thumb { background: #333; border-radius: 3px; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<!-- Left Panel: Remote -->\n"
"<div id=\"panel-remote\">\n"
"  <div id=\"video-wrapper\">\n"
"    <video id=\"remote-video\" autoplay muted playsinline></video>\n"
"    <canvas id=\"touch-overlay\"></canvas>\n"
"    <div id=\"video-loading\">\n"
"      <div class=\"spinner\"></div>\n"
"      <div>Loading video stream...</div>\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"btn-bar\">\n"
"    <button onclick=\"sendKey('back')\">Back</button>\n"
"    <button onclick=\"sendKey('home')\">Home</button>\n"
"    <button onclick=\"sendKey('app_switch')\">Recents</button>\n"
"    <button onclick=\"sendKey('volume_up')\">Vol+</button>\n"
"    <button onclick=\"sendKey('volume_down')\">Vol-</button>\n"
"    <button onclick=\"sendKey('power')\">Power</button>\n"
"  </div>\n"
"  <div id=\"remote-status\">Not connected</div>\n"
"</div>\n"
"\n"
"<!-- Right Panel: AI -->\n"
"<div id=\"panel-ai\">\n"
"  <header>\n"
"    <h1>scrcpy AI Control</h1>\n"
"    <span class=\"status\" id=\"status\">Connecting...</span>\n"
"  </header>\n"
"  <div class=\"ai-container\">\n"
"    <!-- Tab Bar -->\n"
"    <div class=\"tab-bar\">\n"
"      <button class=\"tab-btn active\" onclick=\"switchTab('chat')\">Chat</button>\n"
"      <button class=\"tab-btn\" onclick=\"switchTab('learn')\">Learn</button>\n"
"      <button class=\"tab-btn\" onclick=\"switchTab('auto')\">Auto</button>\n"
"    </div>\n"
"\n"
"    <!-- Chat Tab -->\n"
"    <div class=\"tab-content active\" id=\"tab-chat\">\n"
"      <div id=\"chat-area\">\n"
"        <div id=\"chat-history\"></div>\n"
"        <div id=\"prompt-row\">\n"
"          <textarea id=\"prompt-input\" rows=\"2\" placeholder=\"Enter prompt...\"\n"
"            onkeydown=\"if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();sendPrompt()}\"></textarea>\n"
"          <div class=\"chat-buttons\">\n"
"            <button onclick=\"sendPrompt()\">Send</button>\n"
"            <button class=\"secondary\" onclick=\"clearHistory()\">Clear</button>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Learn Tab -->\n"
"    <div class=\"tab-content\" id=\"tab-learn\">\n"
"      <h3 style=\"margin-bottom:6px;font-size:14px\">Game Rules</h3>\n"
"      <p style=\"font-size:11px;color:#888;margin-bottom:10px\">"
"Edit the game rules below. The AI will follow these rules during auto-play.</p>\n"
"      <textarea id=\"rules-textarea\" placeholder=\"Enter game rules here...\\n\\n"
"Example:\\n- Tap matching tiles to clear them\\n- Prioritize combos\\n- Avoid hitting bombs\"></textarea>\n"
"      <div class=\"learn-buttons\">\n"
"        <button class=\"secondary\" onclick=\"summarizeRules()\">Summarize from Chat</button>\n"
"        <button class=\"success\" onclick=\"saveRules()\">Save</button>\n"
"        <span id=\"summarize-status\"></span>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Auto Tab -->\n"
"    <div class=\"tab-content\" id=\"tab-auto\">\n"
"      <div class=\"auto-card\">\n"
"        <h3>AI Auto-Play</h3>\n"
"        <div class=\"auto-controls\">\n"
"          <label style=\"font-size:12px;color:#aaa\">Interval:</label>\n"
"          <select id=\"auto-interval\">\n"
"            <option value=\"5000\" selected>5s</option>\n"
"            <option value=\"10000\">10s</option>\n"
"            <option value=\"15000\">15s</option>\n"
"          </select>\n"
"          <button id=\"auto-start-btn\" class=\"success\" onclick=\"startAuto()\">Start Auto-Play</button>\n"
"          <button id=\"auto-stop-btn\" class=\"danger\" onclick=\"stopAuto()\" disabled>Stop</button>\n"
"        </div>\n"
"        <div class=\"auto-info\">\n"
"          <span><span class=\"label\">Status: </span>"
"<span class=\"value stopped\" id=\"auto-status-text\">Stopped</span></span>\n"
"          <span><span class=\"label\">Rules: </span>"
"<span id=\"auto-rules-preview\" style=\"color:#ccc\">Not set</span></span>\n"
"        </div>\n"
"      </div>\n"
"      <!-- Activity Log -->\n"
"      <div class=\"auto-log-card\">\n"
"        <div class=\"auto-log-header\">\n"
"          <span>Activity Log</span>\n"
"          <button class=\"secondary\" onclick=\"clearAutoLog()\">Clear</button>\n"
"        </div>\n"
"        <div id=\"auto-log-list\"></div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Settings (collapsible, shown on all tabs) -->\n"
"    <div class=\"panel\" style=\"margin:0 10px 10px;flex-shrink:0\">\n"
"      <div class=\"panel-header\" onclick=\"togglePanel(this)\">\n"
"        <span>Settings</span><span class=\"arrow\">&#9654;</span>\n"
"      </div>\n"
"      <div class=\"panel-body collapsed\">\n"
"        <div class=\"setting-row\">\n"
"          <label>API Key</label>\n"
"          <input id=\"cfg-api-key\" type=\"password\" placeholder=\"sk-...\">\n"
"        </div>\n"
"        <div class=\"setting-row\">\n"
"          <label>Model</label>\n"
"          <input id=\"cfg-model\" placeholder=\"google/gemma-3-27b-it:free\">\n"
"        </div>\n"
"        <div class=\"setting-row\">\n"
"          <label>Base URL</label>\n"
"          <input id=\"cfg-base-url\" placeholder=\"https://openrouter.ai/api/v1\">\n"
"        </div>\n"
"        <button onclick=\"applySettings()\" style=\"margin-top:4px\">Apply</button>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<script src=\"https://cdn.jsdelivr.net/npm/jmuxer@2.0.5/dist/jmuxer.min.js\"></script>\n"
"<script>\n"
"/* =================== AI Panel Logic (existing) =================== */\n"
"let lastMsgCount = 0;\n"
"let pollTimer = null;\n"
"let currentTab = 'chat';\n"
"let autoLogMsgIndex = 0;\n"
"\n"
"function switchTab(tab) {\n"
"  currentTab = tab;\n"
"  document.querySelectorAll('.tab-btn').forEach((btn, i) => {\n"
"    const tabs = ['chat', 'learn', 'auto'];\n"
"    btn.classList.toggle('active', tabs[i] === tab);\n"
"  });\n"
"  document.querySelectorAll('.tab-content').forEach(el => {\n"
"    el.classList.toggle('active', el.id === 'tab-' + tab);\n"
"  });\n"
"}\n"
"\n"
"function togglePanel(header) {\n"
"  const body = header.nextElementSibling;\n"
"  body.classList.toggle('collapsed');\n"
"  const arrow = header.querySelector('.arrow');\n"
"  if (arrow) arrow.textContent = body.classList.contains('collapsed') ? '\\u25B6' : '\\u25BC';\n"
"}\n"
"\n"
"async function api(method, path, body) {\n"
"  try {\n"
"    const opts = { method };\n"
"    if (body !== undefined) {\n"
"      opts.headers = {'Content-Type': 'application/json'};\n"
"      opts.body = JSON.stringify(body);\n"
"    }\n"
"    const r = await fetch(path, opts);\n"
"    if (!r.ok) throw new Error(r.statusText);\n"
"    return await r.json();\n"
"  } catch(e) {\n"
"    console.error('API error:', e);\n"
"    return null;\n"
"  }\n"
"}\n"
"\n"
"function escapeHtml(s) {\n"
"  const d = document.createElement('div');\n"
"  d.textContent = s;\n"
"  return d.innerHTML;\n"
"}\n"
"\n"
"function fmtTime() {\n"
"  const d = new Date();\n"
"  const pad = n => String(n).padStart(2,'0');\n"
"  return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())\n"
"    +' '+pad(d.getHours())+':'+pad(d.getMinutes())+':'+pad(d.getSeconds());\n"
"}\n"
"\n"
"function formatToolCall(tc) {\n"
"  try {\n"
"    const fn = tc.function ? tc.function.name : '';\n"
"    const raw = tc.function ? tc.function.arguments : '{}';\n"
"    const a = JSON.parse(raw);\n"
"    if (fn === 'position_click') return 'click ['+a.x+','+a.y+']';\n"
"    if (fn === 'position_long_press') return 'long_press ['+a.x+','+a.y+'] '+(a.duration_ms||500)+'ms';\n"
"    if (fn === 'swipe') return 'swipe ['+a.x1+','+a.y1+'\\u2192'+a.x2+','+a.y2+']';\n"
"    if (fn === 'key_press') return 'key ['+a.keycode+']';\n"
"    if (fn === 'key_down') return 'key_down ['+a.keycode+']';\n"
"    if (fn === 'key_up') return 'key_up ['+a.keycode+']';\n"
"    if (fn === 'input_text') return 'text \\\"'+(a.text||'').substring(0,30)+'\\\"';\n"
"    if (fn === 'screenshot') return 'screenshot';\n"
"    return fn+'('+raw.substring(0,40)+')';\n"
"  } catch(e) { return '(parse error)'; }\n"
"}\n"
"\n"
"function appendAutoLog(messages) {\n"
"  if (!messages || messages.length <= autoLogMsgIndex) return;\n"
"  const logEl = document.getElementById('auto-log-list');\n"
"  const wasAtBottom = logEl.scrollTop + logEl.clientHeight >= logEl.scrollHeight - 20;\n"
"  const ts = fmtTime();\n"
"\n"
"  for (let i = autoLogMsgIndex; i < messages.length; i++) {\n"
"    const m = messages[i];\n"
"    if (m.role === 'system') continue;\n"
"\n"
"    if (m.role === 'assistant') {\n"
"      const div = document.createElement('div');\n"
"      div.className = 'log-entry';\n"
"      let html = '<span class=\"log-ts\">['+escapeHtml(ts)+']</span> ';\n"
"\n"
"      if (m.content && m.content.trim()) {\n"
"        const text = m.content.length > 120 ? m.content.substring(0,120)+'...' : m.content;\n"
"        html += '<span class=\"log-ai\">AI:</span> ';\n"
"        html += '<span class=\"log-ai-text\">\\\"'+escapeHtml(text)+'\\\"</span>';\n"
"      }\n"
"\n"
"      if (m.tool_calls) {\n"
"        try {\n"
"          const tcs = JSON.parse(m.tool_calls);\n"
"          if (Array.isArray(tcs) && tcs.length > 0) {\n"
"            if (m.content && m.content.trim()) html += '<br>';\n"
"            const parts = tcs.map(formatToolCall);\n"
"            html += '<span class=\"log-ts\">['+escapeHtml(ts)+']</span> ';\n"
"            html += '<span class=\"log-tool\">Tool:</span> ';\n"
"            html += '<span class=\"log-tool-detail\">'+escapeHtml(parts.join(' | '))+'</span>';\n"
"          }\n"
"        } catch(e) {}\n"
"      }\n"
"\n"
"      div.innerHTML = html;\n"
"      logEl.appendChild(div);\n"
"    }\n"
"  }\n"
"  autoLogMsgIndex = messages.length;\n"
"  if (wasAtBottom) logEl.scrollTop = logEl.scrollHeight;\n"
"}\n"
"\n"
"function clearAutoLog() {\n"
"  document.getElementById('auto-log-list').innerHTML = '';\n"
"}\n"
"\n"
"function renderMessages(messages) {\n"
"  const el = document.getElementById('chat-history');\n"
"  const atBottom = el.scrollTop + el.clientHeight >= el.scrollHeight - 30;\n"
"  el.innerHTML = '';\n"
"  for (const m of messages) {\n"
"    if (m.role === 'system') continue;\n"
"    let cls = 'msg-' + m.role;\n"
"    let role = m.role === 'user' ? 'You' : m.role === 'assistant' ? 'AI' : (m.name || 'tool');\n"
"    const div = document.createElement('div');\n"
"    div.className = 'msg ' + cls;\n"
"    div.innerHTML = '<div class=\"msg-role\">' + escapeHtml(role) + '</div>' + escapeHtml(m.content || '');\n"
"    el.appendChild(div);\n"
"  }\n"
"  if (atBottom || messages.length !== lastMsgCount) {\n"
"    el.scrollTop = el.scrollHeight;\n"
"    lastMsgCount = messages.length;\n"
"  }\n"
"}\n"
"\n"
"function renderAutoState(autoRunning, intervalMs, gameRules) {\n"
"  const statusEl = document.getElementById('auto-status-text');\n"
"  const startBtn = document.getElementById('auto-start-btn');\n"
"  const stopBtn = document.getElementById('auto-stop-btn');\n"
"  const previewEl = document.getElementById('auto-rules-preview');\n"
"  if (autoRunning) {\n"
"    statusEl.textContent = 'Running (every ' + (intervalMs/1000) + 's)';\n"
"    statusEl.className = 'value';\n"
"    startBtn.disabled = true;\n"
"    stopBtn.disabled = false;\n"
"  } else {\n"
"    statusEl.textContent = 'Stopped';\n"
"    statusEl.className = 'value stopped';\n"
"    startBtn.disabled = false;\n"
"    stopBtn.disabled = true;\n"
"  }\n"
"  if (gameRules && gameRules.trim()) {\n"
"    const preview = gameRules.length > 60 ? gameRules.substring(0, 60) + '...' : gameRules;\n"
"    previewEl.textContent = preview;\n"
"  } else {\n"
"    previewEl.textContent = 'Not set';\n"
"  }\n"
"}\n"
"\n"
"let rulesLoaded = false;\n"
"async function pollState() {\n"
"  const s = await api('GET', '/api/state');\n"
"  if (!s) {\n"
"    document.getElementById('status').textContent = 'Disconnected';\n"
"    return;\n"
"  }\n"
"  document.getElementById('status').textContent =\n"
"    'Connected | ' + (s.screen_width||0) + 'x' + (s.screen_height||0);\n"
"  renderMessages(s.messages || []);\n"
"  renderAutoState(s.auto_running, s.auto_interval_ms, s.game_rules);\n"
"  appendAutoLog(s.messages || []);\n"
"  if (!rulesLoaded && s.game_rules) {\n"
"    document.getElementById('rules-textarea').value = s.game_rules;\n"
"    rulesLoaded = true;\n"
"  }\n"
"  const ak = document.getElementById('cfg-api-key');\n"
"  if (!ak.value && s.config_api_key) ak.value = s.config_api_key;\n"
"  const md = document.getElementById('cfg-model');\n"
"  if (!md.value && s.config_model) md.value = s.config_model;\n"
"  const bu = document.getElementById('cfg-base-url');\n"
"  if (!bu.value && s.config_base_url) bu.value = s.config_base_url;\n"
"}\n"
"\n"
"async function sendPrompt() {\n"
"  const el = document.getElementById('prompt-input');\n"
"  const text = el.value.trim();\n"
"  if (!text) return;\n"
"  el.value = '';\n"
"  await api('POST', '/api/prompt', {prompt: text});\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function clearHistory() {\n"
"  await api('POST', '/api/clear');\n"
"  autoLogMsgIndex = 0;\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function saveRules() {\n"
"  const rules = document.getElementById('rules-textarea').value;\n"
"  await api('POST', '/api/game-rules', {rules: rules});\n"
"  document.getElementById('summarize-status').textContent = 'Saved!';\n"
"  setTimeout(() => { document.getElementById('summarize-status').textContent = ''; }, 2000);\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function summarizeRules() {\n"
"  const statusEl = document.getElementById('summarize-status');\n"
"  statusEl.textContent = 'Summarizing...';\n"
"  const result = await api('POST', '/api/game-rules/summarize');\n"
"  if (result && result.rules) {\n"
"    document.getElementById('rules-textarea').value = result.rules;\n"
"    statusEl.textContent = 'Done! Review and save.';\n"
"  } else {\n"
"    statusEl.textContent = 'Failed to summarize.';\n"
"  }\n"
"  setTimeout(() => { statusEl.textContent = ''; }, 3000);\n"
"}\n"
"\n"
"async function startAuto() {\n"
"  const interval = parseInt(document.getElementById('auto-interval').value);\n"
"  await api('POST', '/api/auto/start', {interval_ms: interval});\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function stopAuto() {\n"
"  await api('POST', '/api/auto/stop');\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function applySettings() {\n"
"  const api_key = document.getElementById('cfg-api-key').value;\n"
"  const model = document.getElementById('cfg-model').value;\n"
"  const base_url = document.getElementById('cfg-base-url').value;\n"
"  await api('POST', '/api/config', {api_key, model, base_url});\n"
"}\n"
"\n"
"// Start polling\n"
"pollState();\n"
"pollTimer = setInterval(pollState, 2000);\n"
"\n"
"/* =================== Remote Panel Logic =================== */\n"
"let deviceWidth = 0, deviceHeight = 0;\n"
"let jmuxerInstance = null;\n"
"let videoWs = null;\n"
"let controlWs = null;\n"
"let videoStarted = false;\n"
"\n"
"function initVideoWs() {\n"
"  const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"  const url = proto + '//' + location.host + '/ws/video';\n"
"  videoWs = new WebSocket(url);\n"
"  videoWs.binaryType = 'arraybuffer';\n"
"\n"
"  videoWs.onopen = () => {\n"
"    document.getElementById('remote-status').textContent = 'Video: Connected';\n"
"    videoStarted = false;\n"
"    document.getElementById('video-loading').style.display = 'flex';\n"
"  };\n"
"\n"
"  videoWs.onmessage = (evt) => {\n"
"    if (typeof evt.data === 'string') {\n"
"      try {\n"
"        const info = JSON.parse(evt.data);\n"
"        deviceWidth = info.width || 0;\n"
"        deviceHeight = info.height || 0;\n"
"        document.getElementById('remote-status').textContent =\n"
"          'Video: ' + deviceWidth + 'x' + deviceHeight;\n"
"        resizeOverlay();\n"
"      } catch(e) {}\n"
"      return;\n"
"    }\n"
"    // Binary H.264 data — already Annex-B from server\n"
"    if (jmuxerInstance) {\n"
"      var data = new Uint8Array(evt.data);\n"
"      frameCount++;\n"
"      try {\n"
"        jmuxerInstance.feed({ video: data });\n"
"      } catch(e) {\n"
"        console.error('jmuxer feed error:', e, 'frame:', frameCount, 'size:', data.length);\n"
"      }\n"
"      // Sync playback position to live edge\n"
"      var vid = document.getElementById('remote-video');\n"
"      if (vid.buffered.length > 0) {\n"
"        var end = vid.buffered.end(vid.buffered.length - 1);\n"
"        if (end - vid.currentTime > 0.5) {\n"
"          vid.currentTime = end - 0.1;\n"
"        }\n"
"        if (vid.paused) vid.play().catch(function(){});\n"
"      }\n"
"      if (frameCount % 30 === 0) {\n"
"        document.getElementById('remote-status').textContent =\n"
"          'Video: ' + deviceWidth + 'x' + deviceHeight + ' | Frames: ' + frameCount;\n"
"      }\n"
"    }\n"
"  };\n"
"\n"
"  videoWs.onclose = () => {\n"
"    document.getElementById('remote-status').textContent = 'Video: Disconnected';\n"
"    setTimeout(initVideoWs, 3000);\n"
"  };\n"
"\n"
"  videoWs.onerror = () => {\n"
"    videoWs.close();\n"
"  };\n"
"}\n"
"\n"
"function initControlWs() {\n"
"  const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"  const url = proto + '//' + location.host + '/ws/control';\n"
"  controlWs = new WebSocket(url);\n"
"\n"
"  controlWs.onclose = () => {\n"
"    setTimeout(initControlWs, 3000);\n"
"  };\n"
"\n"
"  controlWs.onerror = () => {\n"
"    controlWs.close();\n"
"  };\n"
"}\n"
"\n"
"function sendKey(key) {\n"
"  if (controlWs && controlWs.readyState === WebSocket.OPEN) {\n"
"    controlWs.send(JSON.stringify({type:'key', key: key}));\n"
"  }\n"
"}\n"
"\n"
"function sendTouch(action, clientX, clientY) {\n"
"  var dbg = document.getElementById('remote-status');\n"
"  if (!controlWs || controlWs.readyState !== WebSocket.OPEN) {\n"
"    dbg.textContent = 'Touch: WS not open';\n"
"    return;\n"
"  }\n"
"\n"
"  const video = document.getElementById('remote-video');\n"
"  // Use live video dimensions (updates on rotation)\n"
"  const vw = video.videoWidth || deviceWidth;\n"
"  const vh = video.videoHeight || deviceHeight;\n"
"  if (!vw || !vh) {\n"
"    dbg.textContent = 'Touch: no dimensions';\n"
"    return;\n"
"  }\n"
"\n"
"  const wrapper = document.getElementById('video-wrapper');\n"
"  const wrapperRect = wrapper.getBoundingClientRect();\n"
"  const wW = wrapperRect.width;\n"
"  const wH = wrapperRect.height;\n"
"\n"
"  let renderW, renderH;\n"
"  if (vw / vh > wW / wH) {\n"
"    renderW = wW;\n"
"    renderH = wW * vh / vw;\n"
"  } else {\n"
"    renderH = wH;\n"
"    renderW = wH * vw / vh;\n"
"  }\n"
"\n"
"  const offsetX = (wW - renderW) / 2;\n"
"  const offsetY = (wH - renderH) / 2;\n"
"\n"
"  // Position relative to wrapper\n"
"  const relX = clientX - wrapperRect.left - offsetX;\n"
"  const relY = clientY - wrapperRect.top - offsetY;\n"
"\n"
"  // Clamp to video area\n"
"  const normX = Math.max(0, Math.min(1, relX / renderW));\n"
"  const normY = Math.max(0, Math.min(1, relY / renderH));\n"
"\n"
"  // Map to device coordinates using actual video dimensions\n"
"  const x = Math.round(normX * vw);\n"
"  const y = Math.round(normY * vh);\n"
"\n"
"  var msg = {type:'touch', action:action, x:x, y:y, w:vw, h:vh};\n"
"  controlWs.send(JSON.stringify(msg));\n"
"  dbg.textContent = 'Touch: ' + action + ' ' + x + ',' + y + ' (' + vw + 'x' + vh + ')';\n"
"}\n"
"\n"
"function resizeOverlay() {\n"
"  const canvas = document.getElementById('touch-overlay');\n"
"  const wrapper = document.getElementById('video-wrapper');\n"
"  canvas.width = wrapper.clientWidth;\n"
"  canvas.height = wrapper.clientHeight;\n"
"}\n"
"\n"
"// Touch/mouse events on canvas overlay\n"
"(function() {\n"
"  const overlay = document.getElementById('touch-overlay');\n"
"  let isDown = false;\n"
"\n"
"  // Mouse events\n"
"  overlay.addEventListener('mousedown', (e) => {\n"
"    e.preventDefault();\n"
"    isDown = true;\n"
"    console.log('mousedown', e.clientX, e.clientY);\n"
"    sendTouch('down', e.clientX, e.clientY);\n"
"  });\n"
"  overlay.addEventListener('mousemove', (e) => {\n"
"    if (!isDown) return;\n"
"    e.preventDefault();\n"
"    sendTouch('move', e.clientX, e.clientY);\n"
"  });\n"
"  overlay.addEventListener('mouseup', (e) => {\n"
"    if (!isDown) return;\n"
"    isDown = false;\n"
"    e.preventDefault();\n"
"    sendTouch('up', e.clientX, e.clientY);\n"
"  });\n"
"  overlay.addEventListener('mouseleave', (e) => {\n"
"    if (!isDown) return;\n"
"    isDown = false;\n"
"    sendTouch('up', e.clientX, e.clientY);\n"
"  });\n"
"\n"
"  // Touch events\n"
"  overlay.addEventListener('touchstart', (e) => {\n"
"    e.preventDefault();\n"
"    const t = e.touches[0];\n"
"    isDown = true;\n"
"    sendTouch('down', t.clientX, t.clientY);\n"
"  });\n"
"  overlay.addEventListener('touchmove', (e) => {\n"
"    e.preventDefault();\n"
"    const t = e.touches[0];\n"
"    sendTouch('move', t.clientX, t.clientY);\n"
"  });\n"
"  overlay.addEventListener('touchend', (e) => {\n"
"    e.preventDefault();\n"
"    isDown = false;\n"
"    const t = e.changedTouches[0];\n"
"    sendTouch('up', t.clientX, t.clientY);\n"
"  });\n"
"  overlay.addEventListener('touchcancel', (e) => {\n"
"    e.preventDefault();\n"
"    isDown = false;\n"
"    const t = e.changedTouches[0];\n"
"    sendTouch('up', t.clientX, t.clientY);\n"
"  });\n"
"\n"
"  window.addEventListener('resize', resizeOverlay);\n"
"})();\n"
"\n"
"let frameCount = 0;\n"
"\n"
"// Initialize jmuxer + WebSockets\n"
"(function() {\n"
"  const statusEl = document.getElementById('remote-status');\n"
"  if (typeof JMuxer === 'undefined') {\n"
"    statusEl.textContent = 'Error: jmuxer.js not loaded';\n"
"    return;\n"
"  }\n"
"\n"
"  // Check MSE support\n"
"  if (typeof MediaSource === 'undefined') {\n"
"    statusEl.textContent = 'Error: MediaSource API not supported';\n"
"    return;\n"
"  }\n"
"\n"
"  const codec = 'video/mp4; codecs=\\\"avc1.640028\\\"';\n"
"  if (!MediaSource.isTypeSupported(codec)) {\n"
"    statusEl.textContent = 'Error: H.264 codec not supported by browser';\n"
"    return;\n"
"  }\n"
"\n"
"  try {\n"
"    jmuxerInstance = new JMuxer({\n"
"      node: 'remote-video',\n"
"      mode: 'video',\n"
"      flushingTime: 100,\n"
"      fps: 30,\n"
"      debug: true,\n"
"      onReady: function() {\n"
"        console.log('JMuxer ready');\n"
"        statusEl.textContent = 'JMuxer ready, waiting for video...';\n"
"      },\n"
"      onError: function(err) {\n"
"        console.error('JMuxer error:', err);\n"
"        statusEl.textContent = 'JMuxer error: ' + (err.message || err);\n"
"      }\n"
"    });\n"
"    statusEl.textContent = 'JMuxer initialized, connecting...';\n"
"  } catch(e) {\n"
"    statusEl.textContent = 'JMuxer init error: ' + e.message;\n"
"    return;\n"
"  }\n"
"\n"
"  // Hide loading overlay only when video actually renders frames\n"
"  var remoteVid = document.getElementById('remote-video');\n"
"  remoteVid.addEventListener('timeupdate', function() {\n"
"    if (!videoStarted && remoteVid.currentTime > 0) {\n"
"      videoStarted = true;\n"
"      document.getElementById('video-loading').style.display = 'none';\n"
"    }\n"
"  });\n"
"\n"
"  initVideoWs();\n"
"  initControlWs();\n"
"  resizeOverlay();\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif
