#ifndef SC_WEB_UI_H
#define SC_WEB_UI_H

static const char WEB_UI_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>scrcpy AI Control</title>\n"
"<style>\n"
"* { margin: 0; padding: 0; box-sizing: border-box; }\n"
":root {\n"
"  --bg-0: #080b14;\n"
"  --bg-1: #0f1526;\n"
"  --bg-2: #151e33;\n"
"  --card: rgba(17, 25, 44, 0.82);\n"
"  --line: rgba(120, 148, 215, 0.25);\n"
"  --text: #ecf0ff;\n"
"  --text-dim: #9aa8cc;\n"
"  --accent-2: #36d5ff;\n"
"  --good: #2fd49c;\n"
"  --warn: #ffc857;\n"
"  --bad: #ff5f7d;\n"
"}\n"
"body {\n"
"  font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
"  color: var(--text);\n"
"  background:\n"
"    radial-gradient(1000px 600px at -10% -20%, rgba(54, 213, 255, 0.18), transparent 55%),\n"
"    radial-gradient(900px 500px at 110% 120%, rgba(123, 140, 255, 0.14), transparent 55%),\n"
"    linear-gradient(135deg, var(--bg-0), var(--bg-1) 45%, var(--bg-2));\n"
"  height: 100vh;\n"
"  display: flex;\n"
"  gap: 10px;\n"
"  padding: 10px;\n"
"  margin: 0;\n"
"}\n"
"\n"
"/* Left panel: Remote */\n"
"#panel-remote {\n"
"  flex: 7;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  min-width: 0;\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 16px;\n"
"  overflow: hidden;\n"
"  background: var(--card);\n"
"  backdrop-filter: blur(12px);\n"
"  box-shadow: 0 14px 40px rgba(0, 0, 0, 0.45);\n"
"}\n"
"#video-wrapper {\n"
"  flex: 1;\n"
"  display: flex;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  background: radial-gradient(circle at 50% 10%, #0f1628 10%, #02040a 80%);\n"
"  min-height: 0;\n"
"  position: relative;\n"
"  overflow: hidden;\n"
"}\n"
"#remote-video { max-width: 100%; max-height: 100%; object-fit: contain; display: block; }\n"
"#remote-video.rotated { position: absolute; top: 50%; left: 50%; max-width: none; max-height: none; object-fit: fill; }\n"
"#touch-overlay { position: absolute; inset: 0; cursor: crosshair; touch-action: none; }\n"
"#video-loading {\n"
"  position: absolute;\n"
"  inset: 0;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  background: rgba(0, 0, 0, 0.6);\n"
"  color: var(--text-dim);\n"
"  font-size: 14px;\n"
"  z-index: 10;\n"
"  pointer-events: none;\n"
"}\n"
"#video-loading .spinner {\n"
"  width: 44px;\n"
"  height: 44px;\n"
"  border: 3px solid rgba(123, 140, 255, 0.2);\n"
"  border-top: 3px solid var(--accent-2);\n"
"  border-radius: 50%;\n"
"  animation: spin 1s linear infinite;\n"
"  margin-bottom: 12px;\n"
"}\n"
"@keyframes spin { to { transform: rotate(360deg); } }\n"
"\n"
".btn-bar {\n"
"  display: flex;\n"
"  gap: 6px;\n"
"  padding: 10px;\n"
"  background: linear-gradient(180deg, rgba(20, 29, 51, 0.95), rgba(14, 21, 38, 0.95));\n"
"  border-top: 1px solid var(--line);\n"
"  flex-wrap: wrap;\n"
"  justify-content: center;\n"
"}\n"
".btn-bar button {\n"
"  padding: 7px 12px;\n"
"  font-size: 12px;\n"
"  background: linear-gradient(180deg, rgba(123, 140, 255, 0.22), rgba(90, 105, 214, 0.18));\n"
"  color: var(--text);\n"
"  border: 1px solid rgba(123, 140, 255, 0.35);\n"
"  border-radius: 10px;\n"
"  cursor: pointer;\n"
"  font-weight: 600;\n"
"  transition: transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease;\n"
"}\n"
".btn-bar button:hover {\n"
"  border-color: rgba(123, 140, 255, 0.65);\n"
"  box-shadow: 0 0 0 2px rgba(123, 140, 255, 0.18);\n"
"  transform: translateY(-1px);\n"
"}\n"
".btn-bar button:active { transform: translateY(0); }\n"
"\n"
"#remote-status {\n"
"  padding: 7px 10px;\n"
"  font-size: 11px;\n"
"  color: var(--text-dim);\n"
"  background: rgba(8, 12, 24, 0.88);\n"
"  text-align: center;\n"
"  border-top: 1px solid var(--line);\n"
"  letter-spacing: 0.02em;\n"
"}\n"
"\n"
"/* Right panel: AI */\n"
"#panel-ai {\n"
"  flex: 3;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  min-width: 0;\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 16px;\n"
"  overflow: hidden;\n"
"  background: var(--card);\n"
"  backdrop-filter: blur(12px);\n"
"  box-shadow: 0 14px 40px rgba(0, 0, 0, 0.45);\n"
"}\n"
"#panel-ai header {\n"
"  background: linear-gradient(135deg, rgba(22, 30, 54, 0.95), rgba(18, 27, 49, 0.95));\n"
"  padding: 12px 16px;\n"
"  border-bottom: 1px solid var(--line);\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: space-between;\n"
"}\n"
"#panel-ai header h1 {\n"
"  font-size: 15px;\n"
"  font-weight: 700;\n"
"  color: var(--text);\n"
"  letter-spacing: 0.01em;\n"
"}\n"
"#panel-ai header .header-actions {\n"
"  display: flex;\n"
"  align-items: center;\n"
"  gap: 8px;\n"
"}\n"
"#open-settings-btn {\n"
"  width: 34px;\n"
"  height: 34px;\n"
"  padding: 0;\n"
"  border-radius: 10px;\n"
"  display: inline-flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  background: rgba(123, 140, 255, 0.14);\n"
"  border: 1px solid rgba(123, 140, 255, 0.35);\n"
"}\n"
"#open-settings-btn:hover {\n"
"  box-shadow: 0 0 0 2px rgba(123, 140, 255, 0.2);\n"
"}\n"
"#open-settings-btn.disconnected {\n"
"  background: rgba(255, 95, 125, 0.14);\n"
"  border-color: rgba(255, 95, 125, 0.45);\n"
"}\n"
".settings-icon {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  fill: none;\n"
"  stroke: currentColor;\n"
"  stroke-width: 2;\n"
"  color: var(--text);\n"
"}\n"
".ai-container { flex: 1; display: flex; flex-direction: column; overflow: hidden; }\n"
"\n"
"/* Tabs */\n"
".tab-bar {\n"
"  display: grid;\n"
"  grid-template-columns: repeat(3, minmax(0, 1fr));\n"
"  gap: 6px;\n"
"  padding: 8px 10px;\n"
"  border-bottom: 1px solid var(--line);\n"
"  background: rgba(11, 16, 31, 0.7);\n"
"}\n"
".tab-btn {\n"
"  padding: 9px;\n"
"  text-align: center;\n"
"  font-size: 12px;\n"
"  font-weight: 700;\n"
"  cursor: pointer;\n"
"  border: 1px solid transparent;\n"
"  background: rgba(255, 255, 255, 0.02);\n"
"  color: var(--text-dim);\n"
"  border-radius: 10px;\n"
"  transition: all 0.18s ease;\n"
"}\n"
".tab-btn:hover {\n"
"  color: var(--text);\n"
"  border-color: rgba(123, 140, 255, 0.3);\n"
"  background: rgba(123, 140, 255, 0.08);\n"
"}\n"
".tab-btn.active {\n"
"  color: #f4f7ff;\n"
"  border-color: rgba(123, 140, 255, 0.7);\n"
"  background: linear-gradient(145deg, rgba(123, 140, 255, 0.35), rgba(54, 213, 255, 0.18));\n"
"}\n"
".tab-content { flex: 1; display: none; flex-direction: column; overflow: hidden; padding: 10px; gap: 10px; }\n"
".tab-content.active { display: flex; }\n"
"\n"
"/* Common */\n"
"button {\n"
"  background: linear-gradient(150deg, #7b8cff, #5e72ff);\n"
"  color: #fff;\n"
"  border: 1px solid rgba(132, 147, 255, 0.65);\n"
"  padding: 8px 14px;\n"
"  border-radius: 10px;\n"
"  cursor: pointer;\n"
"  font-size: 12px;\n"
"  font-weight: 700;\n"
"  transition: transform 0.15s ease, box-shadow 0.15s ease, filter 0.15s ease;\n"
"}\n"
"button:hover {\n"
"  transform: translateY(-1px);\n"
"  box-shadow: 0 8px 20px rgba(69, 92, 255, 0.35);\n"
"}\n"
"button:disabled {\n"
"  background: rgba(120, 130, 160, 0.25);\n"
"  border-color: rgba(120, 130, 160, 0.25);\n"
"  color: #9ba5bf;\n"
"  cursor: not-allowed;\n"
"  box-shadow: none;\n"
"  transform: none;\n"
"}\n"
"button.secondary {\n"
"  background: rgba(115, 136, 198, 0.18);\n"
"  border-color: rgba(115, 136, 198, 0.45);\n"
"}\n"
"button.secondary:hover { box-shadow: 0 8px 18px rgba(90, 110, 180, 0.25); }\n"
"button.danger {\n"
"  background: linear-gradient(150deg, #ff6f8e, #ff4f74);\n"
"  border-color: rgba(255, 128, 154, 0.65);\n"
"}\n"
"button.success {\n"
"  background: linear-gradient(150deg, #35d39f, #20b784);\n"
"  border-color: rgba(89, 231, 178, 0.6);\n"
"}\n"
"select {\n"
"  background: rgba(10, 17, 33, 0.95);\n"
"  border: 1px solid rgba(123, 140, 255, 0.3);\n"
"  color: var(--text);\n"
"  padding: 7px 9px;\n"
"  border-radius: 9px;\n"
"  font-size: 12px;\n"
"  outline: none;\n"
"}\n"
"\n"
"/* Chat tab */\n"
"#chat-area {\n"
"  flex: 1;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  min-height: 0;\n"
"  background: rgba(8, 13, 26, 0.55);\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 12px;\n"
"  padding: 10px;\n"
"}\n"
"#chat-history { flex: 1; overflow-y: auto; margin-bottom: 10px; padding-right: 4px; }\n"
".msg {\n"
"  margin-bottom: 8px;\n"
"  padding: 9px 10px;\n"
"  border-radius: 10px;\n"
"  font-size: 12px;\n"
"  line-height: 1.55;\n"
"  white-space: pre-wrap;\n"
"  word-break: break-word;\n"
"  border: 1px solid transparent;\n"
"}\n"
".msg-user {\n"
"  background: rgba(74, 193, 255, 0.12);\n"
"  border-color: rgba(74, 193, 255, 0.32);\n"
"}\n"
".msg-assistant {\n"
"  background: rgba(79, 255, 176, 0.1);\n"
"  border-color: rgba(79, 255, 176, 0.28);\n"
"}\n"
".msg-tool {\n"
"  background: rgba(255, 200, 74, 0.12);\n"
"  border-color: rgba(255, 200, 74, 0.35);\n"
"  font-size: 11px;\n"
"}\n"
".msg-role {\n"
"  font-weight: 700;\n"
"  font-size: 10px;\n"
"  text-transform: uppercase;\n"
"  margin-bottom: 4px;\n"
"  letter-spacing: 0.04em;\n"
"}\n"
".msg-user .msg-role { color: #7ed2ff; }\n"
".msg-assistant .msg-role { color: #7cffbe; }\n"
".msg-tool .msg-role { color: #ffd989; }\n"
"#prompt-row { display: flex; gap: 8px; }\n"
"#prompt-input {\n"
"  flex: 1;\n"
"  background: rgba(8, 14, 28, 0.95);\n"
"  border: 1px solid rgba(123, 140, 255, 0.25);\n"
"  color: var(--text);\n"
"  padding: 9px;\n"
"  border-radius: 10px;\n"
"  font-size: 13px;\n"
"  outline: none;\n"
"  resize: none;\n"
"  line-height: 1.45;\n"
"}\n"
"#prompt-input:focus {\n"
"  border-color: rgba(54, 213, 255, 0.8);\n"
"  box-shadow: 0 0 0 3px rgba(54, 213, 255, 0.18);\n"
"}\n"
".chat-buttons { display: flex; gap: 6px; }\n"
"\n"
"/* Learn tab */\n"
"#rules-textarea {\n"
"  width: 100%;\n"
"  flex: 1;\n"
"  min-height: 170px;\n"
"  background: rgba(8, 14, 28, 0.95);\n"
"  border: 1px solid rgba(123, 140, 255, 0.25);\n"
"  color: var(--text);\n"
"  padding: 11px;\n"
"  border-radius: 10px;\n"
"  font-size: 12px;\n"
"  font-family: 'SF Mono', 'Consolas', 'Monaco', monospace;\n"
"  outline: none;\n"
"  resize: vertical;\n"
"  line-height: 1.65;\n"
"}\n"
"#rules-textarea:focus {\n"
"  border-color: rgba(54, 213, 255, 0.8);\n"
"  box-shadow: 0 0 0 3px rgba(54, 213, 255, 0.16);\n"
"}\n"
".learn-buttons { display: flex; gap: 8px; margin-top: 9px; align-items: center; flex-wrap: wrap; }\n"
"#summarize-status { font-size: 11px; color: var(--text-dim); margin-left: 2px; }\n"
"\n"
"/* Auto tab */\n"
".auto-card {\n"
"  background: rgba(8, 13, 26, 0.55);\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 12px;\n"
"  padding: 14px;\n"
"  text-align: center;\n"
"  flex-shrink: 0;\n"
"}\n"
".auto-card h3 { margin-bottom: 10px; font-size: 14px; }\n"
".auto-controls {\n"
"  display: flex;\n"
"  gap: 8px;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  flex-wrap: wrap;\n"
"}\n"
".auto-info {\n"
"  display: flex;\n"
"  gap: 14px;\n"
"  margin-top: 12px;\n"
"  justify-content: center;\n"
"  font-size: 12px;\n"
"  flex-wrap: wrap;\n"
"}\n"
".auto-info .label { color: var(--text-dim); }\n"
".auto-info .value { color: var(--good); font-weight: 700; }\n"
".auto-info .value.stopped { color: var(--bad); }\n"
"\n"
"/* Auto log */\n"
".auto-log-card {\n"
"  flex: 1;\n"
"  min-height: 0;\n"
"  background: rgba(8, 13, 26, 0.55);\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 12px;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"}\n"
".auto-log-header {\n"
"  padding: 8px 12px;\n"
"  border-bottom: 1px solid var(--line);\n"
"  font-weight: 700;\n"
"  font-size: 12px;\n"
"  display: flex;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"  flex-shrink: 0;\n"
"}\n"
".auto-log-header button { padding: 4px 9px; font-size: 10px; }\n"
"#auto-log-list, #rec-log-list { flex: 1; overflow-y: auto; padding: 8px 11px; }\n"
".log-entry {\n"
"  padding: 6px 0;\n"
"  border-bottom: 1px dashed rgba(120, 148, 215, 0.2);\n"
"  font-size: 11px;\n"
"  line-height: 1.55;\n"
"  font-family: 'SF Mono', 'Consolas', 'Monaco', monospace;\n"
"}\n"
".log-entry:last-child { border-bottom: none; }\n"
".log-ts { color: #7485b0; }\n"
".log-ai { color: var(--good); }\n"
".log-ai-text { color: #d4dcf2; }\n"
".log-tool { color: var(--warn); }\n"
".log-tool-detail { color: #b8c4e6; }\n"
"\n"
"/* Settings */\n"
".setting-row { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }\n"
".setting-row label { min-width: 70px; font-size: 12px; color: var(--text-dim); }\n"
".setting-row input {\n"
"  flex: 1;\n"
"  background: rgba(8, 14, 28, 0.95);\n"
"  border: 1px solid rgba(123, 140, 255, 0.26);\n"
"  color: var(--text);\n"
"  padding: 7px 9px;\n"
"  border-radius: 9px;\n"
"  font-size: 12px;\n"
"  outline: none;\n"
"}\n"
".setting-row input:focus {\n"
"  border-color: rgba(54, 213, 255, 0.8);\n"
"  box-shadow: 0 0 0 3px rgba(54, 213, 255, 0.14);\n"
"}\n"
"\n"
".settings-modal-backdrop {\n"
"  position: fixed;\n"
"  inset: 0;\n"
"  background: rgba(2, 6, 16, 0.72);\n"
"  backdrop-filter: blur(4px);\n"
"  z-index: 50;\n"
"  display: none;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  padding: 18px;\n"
"}\n"
".settings-modal-backdrop.show { display: flex; }\n"
".settings-modal {\n"
"  width: min(520px, 96vw);\n"
"  background: rgba(15, 22, 40, 0.95);\n"
"  border: 1px solid var(--line);\n"
"  border-radius: 14px;\n"
"  box-shadow: 0 24px 60px rgba(0, 0, 0, 0.45);\n"
"  overflow: hidden;\n"
"}\n"
".settings-modal-header {\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: space-between;\n"
"  padding: 12px 14px;\n"
"  border-bottom: 1px solid var(--line);\n"
"}\n"
".settings-modal-title {\n"
"  font-size: 14px;\n"
"  font-weight: 700;\n"
"}\n"
".settings-modal-body { padding: 12px 14px 8px; }\n"
".settings-modal-actions {\n"
"  padding: 0 14px 14px;\n"
"  display: flex;\n"
"  justify-content: flex-end;\n"
"  gap: 8px;\n"
"}\n"
"\n"
"::-webkit-scrollbar { width: 8px; }\n"
"::-webkit-scrollbar-track { background: transparent; }\n"
"::-webkit-scrollbar-thumb {\n"
"  background: linear-gradient(180deg, rgba(123, 140, 255, 0.65), rgba(54, 213, 255, 0.55));\n"
"  border-radius: 999px;\n"
"}\n"
"\n"
"@media (max-width: 1200px) {\n"
"  body { gap: 8px; padding: 8px; }\n"
"}\n"
"@media (max-width: 960px) {\n"
"  body { flex-direction: column; height: auto; min-height: 100vh; }\n"
"  #panel-remote, #panel-ai { min-height: 360px; }\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<!-- Left Panel: Remote -->\n"
"<div id=\"panel-remote\">\n"
"  <div id=\"video-wrapper\">\n"
"    <video id=\"remote-video\" autoplay muted playsinline></video>\n"
"    <canvas id=\"touch-overlay\"></canvas>\n"
"    <div id=\"video-loading\">\n"
"      <div class=\"spinner\"></div>\n"
"      <div>Loading video stream...</div>\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"btn-bar\">\n"
"    <button onclick=\"sendKey('back')\">Back</button>\n"
"    <button onclick=\"sendKey('home')\">Home</button>\n"
"    <button onclick=\"sendKey('app_switch')\">Recents</button>\n"
"    <button onclick=\"toggleVideoRotation(event)\" title=\"Click: rotate 90deg, Shift+Click: auto\">Rotate</button>\n"
"    <button onclick=\"sendKey('volume_up')\">Vol+</button>\n"
"    <button onclick=\"sendKey('volume_down')\">Vol-</button>\n"
"    <button onclick=\"sendKey('power')\">Power</button>\n"
"  </div>\n"
"  <div id=\"remote-status\">Not connected</div>\n"
"</div>\n"
"\n"
"<!-- Right Panel: AI -->\n"
"<div id=\"panel-ai\">\n"
"  <header>\n"
"    <h1>SCRCPY AI CONTROLLER</h1>\n"
"    <div class=\"header-actions\">\n"
"      <button id=\"open-settings-btn\" title=\"Settings\" aria-label=\"Open settings\" onclick=\"openSettingsModal()\">\n"
"        <svg class=\"settings-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\n"
"          <path d=\"M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7z\"></path>\n"
"          <path d=\"M19.4 15a1 1 0 0 0 .2 1.1l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1 1 0 0 0-1.1-.2 1 1 0 0 0-.6.9V20a2 2 0 1 1-4 0v-.2a1 1 0 0 0-.6-.9 1 1 0 0 0-1.1.2l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1 1 0 0 0 .2-1.1 1 1 0 0 0-.9-.6H4a2 2 0 1 1 0-4h.2a1 1 0 0 0 .9-.6 1 1 0 0 0-.2-1.1l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1 1 0 0 0 1.1.2 1 1 0 0 0 .6-.9V4a2 2 0 1 1 4 0v.2a1 1 0 0 0 .6.9 1 1 0 0 0 1.1-.2l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1 1 0 0 0-.2 1.1 1 1 0 0 0 .9.6h.2a2 2 0 1 1 0 4h-.2a1 1 0 0 0-.9.6z\"></path>\n"
"        </svg>\n"
"      </button>\n"
"    </div>\n"
"  </header>\n"
"  <div class=\"ai-container\">\n"
"    <!-- Tab Bar -->\n"
"    <div class=\"tab-bar\">\n"
"      <button class=\"tab-btn active\" onclick=\"switchTab('record')\">Record</button>\n"
"      <button class=\"tab-btn\" onclick=\"switchTab('train')\">Train</button>\n"
"      <button class=\"tab-btn\" onclick=\"switchTab('play')\">Play</button>\n"
"    </div>\n"
"\n"
"    <!-- Record Tab -->\n"
"    <div class=\"tab-content active\" id=\"tab-record\">\n"
"      <div class=\"auto-card\">\n"
"        <h3>Game Recording</h3>\n"
"        <div class=\"auto-controls\">\n"
"          <button id=\"rec-start-btn\" class=\"success\" onclick=\"startRecording()\">Start Recording</button>\n"
"          <button id=\"rec-stop-btn\" class=\"danger\" onclick=\"stopRecording()\" disabled>Stop</button>\n"
"        </div>\n"
"        <div class=\"auto-info\">\n"
"          <span><span class=\"label\">Status: </span>"
"<span class=\"value stopped\" id=\"rec-status-text\">Stopped</span></span>\n"
"          <span><span class=\"label\">Count: </span>"
"<span class=\"value\" id=\"rec-count-text\">0</span></span>\n"
"        </div>\n"
"      </div>\n"
"      <div class=\"auto-log-card\">\n"
"        <div class=\"auto-log-header\">\n"
"          <span>Record Log</span>\n"
"          <button class=\"secondary\" id=\"rec-clear-btn\" onclick=\"clearRecordLog()\" disabled>Clear</button>\n"
"        </div>\n"
"        <div id=\"rec-log-list\"></div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Train Tab -->\n"
"    <div class=\"tab-content\" id=\"tab-train\">\n"
"      <!-- Session selector bar -->\n"
"      <div style=\"display:flex;gap:6px;align-items:center;margin-bottom:6px\">\n"
"        <select id=\"train-session-select\" style=\"flex:1;background:var(--bg-1);"
"color:var(--text);border:1px solid var(--line);border-radius:6px;padding:4px 8px;"
"font-size:12px\">\n"
"          <option value=\"\">Select session...</option>\n"
"        </select>\n"
"        <button class=\"secondary\" style=\"font-size:11px;padding:3px 8px\" "
"onclick=\"loadTrainSessions()\">Refresh</button>\n"
"        <button style=\"font-size:11px;padding:3px 8px\" "
"onclick=\"loadTrainSession()\">Load</button>\n"
"      </div>\n"
"      <!-- 3:7 split layout -->\n"
"      <div style=\"display:flex;gap:6px;flex:1;min-height:0\">\n"
"        <!-- Left: Tree (30%) -->\n"
"        <div id=\"train-tree-panel\" style=\"flex:3;display:flex;flex-direction:column;"
"background:var(--card);border:1px solid var(--line);border-radius:10px;overflow:hidden\">\n"
"          <div style=\"padding:6px 8px;border-bottom:1px solid var(--line);"
"display:flex;justify-content:space-between;align-items:center\">\n"
"            <span style=\"font-size:12px;font-weight:600\">States</span>\n"
"            <div style=\"display:flex;gap:4px\">\n"
"              <button id=\"train-analyze-btn\" class=\"success\" "
"style=\"font-size:10px;padding:2px 6px\" "
"onclick=\"analyzeAllCaptures()\" disabled>Analyze</button>\n"
"              <button id=\"train-build-btn\" "
"style=\"font-size:10px;padding:2px 6px\" "
"onclick=\"buildDecisionTree()\" disabled>Build</button>\n"
"            </div>\n"
"          </div>\n"
"          <div id=\"train-progress\" style=\"font-size:10px;color:var(--text-dim);"
"padding:2px 8px;display:none\"></div>\n"
"          <div id=\"train-tree-list\" style=\"flex:1;overflow-y:auto;padding:4px;"
"font-size:11px\">\n"
"            <div style=\"color:var(--text-dim);padding:8px\">Load a session to begin</div>\n"
"          </div>\n"
"          <div style=\"padding:4px 6px;border-top:1px solid var(--line);"
"display:flex;gap:4px;flex-wrap:wrap\">\n"
"            <button id=\"train-save-tree-btn\" class=\"success\" "
"style=\"font-size:10px;padding:2px 6px\" "
"onclick=\"saveDecisionTree()\" disabled>Save</button>\n"
"            <button id=\"train-export-btn\" class=\"secondary\" "
"style=\"font-size:10px;padding:2px 6px\" "
"onclick=\"exportTreeJson()\" disabled>Export</button>\n"
"            <button class=\"secondary\" "
"style=\"font-size:10px;padding:2px 6px\" "
"onclick=\"loadDecisionTree()\">Load</button>\n"
"          </div>\n"
"        </div>\n"
"        <!-- Right: Detail (70%) -->\n"
"        <div id=\"train-detail-panel\" style=\"flex:7;display:flex;flex-direction:column;"
"background:var(--card);border:1px solid var(--line);border-radius:10px;overflow:hidden\">\n"
"          <div style=\"padding:6px 8px;border-bottom:1px solid var(--line)\">\n"
"            <span id=\"train-detail-title\" style=\"font-size:12px;font-weight:600\">"
"Detail</span>\n"
"          </div>\n"
"          <div id=\"train-detail-body\" style=\"flex:1;overflow-y:auto;padding:8px\">\n"
"            <div style=\"color:var(--text-dim);font-size:11px\">"
"Select a state or capture from the tree</div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Play Tab -->\n"
"    <div class=\"tab-content\" id=\"tab-play\">\n"
"      <div class=\"auto-card\">\n"
"        <h3>AI Auto-Play</h3>\n"
"        <div class=\"auto-controls\">\n"
"          <button id=\"auto-start-btn\" class=\"success\" onclick=\"startAuto()\">Start Auto-Play</button>\n"
"          <button id=\"auto-stop-btn\" class=\"danger\" onclick=\"stopAuto()\" disabled>Stop</button>\n"
"        </div>\n"
"        <div class=\"auto-info\">\n"
"          <span><span class=\"label\">Status: </span>"
"<span class=\"value stopped\" id=\"auto-status-text\">Stopped</span></span>\n"
"          <span><span class=\"label\">Rules: </span>"
"<span id=\"auto-rules-preview\" style=\"color:#ccc\">Not set</span></span>\n"
"        </div>\n"
"      </div>\n"
"      <!-- Activity Log -->\n"
"      <div class=\"auto-log-card\">\n"
"        <div class=\"auto-log-header\">\n"
"          <span>Activity Log</span>\n"
"          <button class=\"secondary\" onclick=\"clearAutoLog()\">Clear</button>\n"
"        </div>\n"
"        <div id=\"auto-log-list\"></div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"  </div>\n"
"</div>\n"
"\n"
"<div id=\"settings-modal\" class=\"settings-modal-backdrop\" onclick=\"if(event.target===this)closeSettingsModal()\">\n"
"  <div class=\"settings-modal\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"settings-modal-title\">\n"
"    <div class=\"settings-modal-header\">\n"
"      <div class=\"settings-modal-title\" id=\"settings-modal-title\">Settings</div>\n"
"      <button class=\"secondary\" onclick=\"closeSettingsModal()\" aria-label=\"Close settings\">Close</button>\n"
"    </div>\n"
"    <div class=\"settings-modal-body\">\n"
"      <div class=\"setting-row\">\n"
"        <label>API Key</label>\n"
"        <input id=\"cfg-api-key\" type=\"password\" placeholder=\"sk-...\">\n"
"      </div>\n"
"      <div class=\"setting-row\">\n"
"        <label>Game Model</label>\n"
"        <input id=\"cfg-model\" placeholder=\"qwen/qwen3.5-27b\">\n"
"      </div>\n"
"      <div class=\"setting-row\">\n"
"        <label>Vision Model</label>\n"
"        <input id=\"cfg-vision-model\" placeholder=\"google/gemini-2.0-flash-001\">\n"
"      </div>\n"
"      <div class=\"setting-row\">\n"
"        <label>Base URL</label>\n"
"        <input id=\"cfg-base-url\" placeholder=\"https://openrouter.ai/api/v1\">\n"
"      </div>\n"
"    </div>\n"
"    <div class=\"settings-modal-actions\">\n"
"      <button class=\"secondary\" onclick=\"closeSettingsModal()\">Cancel</button>\n"
"      <button onclick=\"applySettings()\">Apply</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<script src=\"https://cdn.jsdelivr.net/npm/jmuxer@2.1.0/dist/jmuxer.min.js\"></script>\n"
"<script>\n"
"/* =================== AI Panel Logic (existing) =================== */\n"
"let lastMsgCount = 0;\n"
"let pollTimer = null;\n"
"let currentTab = 'record';\n"
"let autoLogMsgIndex = 0;\n"
"\n"
"function openSettingsModal() {\n"
"  const modal = document.getElementById('settings-modal');\n"
"  if (!modal) return;\n"
"  modal.classList.add('show');\n"
"}\n"
"\n"
"function closeSettingsModal() {\n"
"  const modal = document.getElementById('settings-modal');\n"
"  if (!modal) return;\n"
"  modal.classList.remove('show');\n"
"}\n"
"\n"
"document.addEventListener('keydown', function(e) {\n"
"  if (e.key === 'Escape') {\n"
"    closeSettingsModal();\n"
"  }\n"
"});\n"
"\n"
"function switchTab(tab) {\n"
"  currentTab = tab;\n"
"  document.querySelectorAll('.tab-btn').forEach((btn, i) => {\n"
"    const tabs = ['record', 'train', 'play'];\n"
"    btn.classList.toggle('active', tabs[i] === tab);\n"
"  });\n"
"  document.querySelectorAll('.tab-content').forEach(el => {\n"
"    el.classList.toggle('active', el.id === 'tab-' + tab);\n"
"  });\n"
"}\n"
"\n"
"async function api(method, path, body) {\n"
"  try {\n"
"    const opts = { method };\n"
"    if (body !== undefined) {\n"
"      opts.headers = {'Content-Type': 'application/json'};\n"
"      opts.body = JSON.stringify(body);\n"
"    }\n"
"    const r = await fetch(path, opts);\n"
"    if (!r.ok) throw new Error(r.statusText);\n"
"    return await r.json();\n"
"  } catch(e) {\n"
"    console.error('API error:', e);\n"
"    return null;\n"
"  }\n"
"}\n"
"\n"
"function escapeHtml(s) {\n"
"  const d = document.createElement('div');\n"
"  d.textContent = s;\n"
"  return d.innerHTML;\n"
"}\n"
"\n"
"function fmtTime() {\n"
"  const d = new Date();\n"
"  const pad = n => String(n).padStart(2,'0');\n"
"  return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())\n"
"    +' '+pad(d.getHours())+':'+pad(d.getMinutes())+':'+pad(d.getSeconds());\n"
"}\n"
"\n"
"function formatToolCall(tc) {\n"
"  try {\n"
"    const fn = tc.function ? tc.function.name : '';\n"
"    const raw = tc.function ? tc.function.arguments : '{}';\n"
"    const a = JSON.parse(raw);\n"
"    if (fn === 'position_click') return 'click ['+a.x+','+a.y+']';\n"
"    if (fn === 'position_long_press') return 'long_press ['+a.x+','+a.y+'] '+(a.duration_ms||500)+'ms';\n"
"    if (fn === 'swipe') return 'swipe ['+a.x1+','+a.y1+'\\u2192'+a.x2+','+a.y2+']';\n"
"    if (fn === 'key_press') return 'key ['+a.keycode+']';\n"
"    if (fn === 'key_down') return 'key_down ['+a.keycode+']';\n"
"    if (fn === 'key_up') return 'key_up ['+a.keycode+']';\n"
"    if (fn === 'input_text') return 'text \\\"'+(a.text||'').substring(0,30)+'\\\"';\n"
"    if (fn === 'screenshot') return 'screenshot';\n"
"    return fn+'('+raw.substring(0,40)+')';\n"
"  } catch(e) { return '(parse error)'; }\n"
"}\n"
"\n"
"function appendAutoLog(messages) {\n"
"  if (!messages || messages.length <= autoLogMsgIndex) return;\n"
"  const logEl = document.getElementById('auto-log-list');\n"
"  const wasAtBottom = logEl.scrollTop + logEl.clientHeight >= logEl.scrollHeight - 20;\n"
"  const ts = fmtTime();\n"
"\n"
"  for (let i = autoLogMsgIndex; i < messages.length; i++) {\n"
"    const m = messages[i];\n"
"    if (m.role === 'system') continue;\n"
"\n"
"    if (m.role === 'assistant') {\n"
"      let hasContent = m.content && m.content.trim();\n"
"      let hasTc = false;\n"
"      let tcParts = [];\n"
"      if (m.tool_calls) {\n"
"        try {\n"
"          const tcs = JSON.parse(m.tool_calls);\n"
"          if (Array.isArray(tcs) && tcs.length > 0) {\n"
"            hasTc = true;\n"
"            tcParts = tcs.map(formatToolCall);\n"
"          }\n"
"        } catch(e) {}\n"
"      }\n"
"      if (!hasContent && !hasTc) continue;\n"
"      const div = document.createElement('div');\n"
"      div.className = 'log-entry';\n"
"      let html = '';\n"
"      if (hasContent) {\n"
"        const text = m.content.length > 120 ? m.content.substring(0,120)+'...' : m.content;\n"
"        html += '<span class=\"log-ts\">['+escapeHtml(ts)+']</span> ';\n"
"        html += '<span class=\"log-ai\">AI:</span> ';\n"
"        html += '<span class=\"log-ai-text\">\\\"'+escapeHtml(text)+'\\\"</span>';\n"
"      }\n"
"      if (hasTc) {\n"
"        if (hasContent) html += '<br>';\n"
"        html += '<span class=\"log-ts\">['+escapeHtml(ts)+']</span> ';\n"
"        html += '<span class=\"log-tool\">Tool:</span> ';\n"
"        html += '<span class=\"log-tool-detail\">'+escapeHtml(tcParts.join(' | '))+'</span>';\n"
"      }\n"
"      div.innerHTML = html;\n"
"      logEl.appendChild(div);\n"
"    } else if (m.role === 'tool') {\n"
"      const div = document.createElement('div');\n"
"      div.className = 'log-entry';\n"
"      const text = (m.content||'').length > 100 ? m.content.substring(0,100)+'...' : (m.content||'');\n"
"      div.innerHTML = '<span class=\"log-ts\">['+escapeHtml(ts)+']</span> '\n"
"        + '<span class=\"log-tool\">Result:</span> '\n"
"        + '<span class=\"log-tool-detail\">'+escapeHtml(text)+'</span>';\n"
"      logEl.appendChild(div);\n"
"    }\n"
"  }\n"
"  autoLogMsgIndex = messages.length;\n"
"  if (wasAtBottom) logEl.scrollTop = logEl.scrollHeight;\n"
"}\n"
"\n"
"function clearAutoLog() {\n"
"  document.getElementById('auto-log-list').innerHTML = '';\n"
"}\n"
"\n"
"/* Recording functions */\n"
"let isRecording = false;\n"
"let recordCount = 0;\n"
"let recordLogEntries = [];\n"
"\n"
"async function startRecording() {\n"
"  const r = await api('POST', '/api/record/start');\n"
"  if (r) {\n"
"    isRecording = true;\n"
"    recordCount = 0;\n"
"    updateRecordUI();\n"
"  }\n"
"}\n"
"\n"
"async function stopRecording() {\n"
"  const r = await api('POST', '/api/record/stop');\n"
"  if (r) {\n"
"    isRecording = false;\n"
"    updateRecordUI();\n"
"  }\n"
"}\n"
"\n"
"function updateRecordUI() {\n"
"  var statusEl = document.getElementById('rec-status-text');\n"
"  var startBtn = document.getElementById('rec-start-btn');\n"
"  var stopBtn = document.getElementById('rec-stop-btn');\n"
"  var countEl = document.getElementById('rec-count-text');\n"
"  var clearBtn = document.getElementById('rec-clear-btn');\n"
"  if (isRecording) {\n"
"    statusEl.textContent = 'Recording';\n"
"    statusEl.className = 'value';\n"
"    startBtn.disabled = true;\n"
"    stopBtn.disabled = false;\n"
"    clearBtn.disabled = true;\n"
"  } else {\n"
"    statusEl.textContent = 'Stopped';\n"
"    statusEl.className = 'value stopped';\n"
"    startBtn.disabled = false;\n"
"    stopBtn.disabled = true;\n"
"    clearBtn.disabled = (recordCount === 0);\n"
"  }\n"
"  countEl.textContent = recordCount;\n"
"}\n"
"\n"
"async function clearRecordLog() {\n"
"  if (isRecording) return;\n"
"  await api('POST', '/api/record/clear');\n"
"  recordLogEntries = [];\n"
"  recordCount = 0;\n"
"  document.getElementById('rec-log-list').innerHTML = '';\n"
"  document.getElementById('rec-count-text').textContent = '0';\n"
"}\n"
"\n"
"function addRecordLogEntry(x, y, w, h, idx) {\n"
"  var el = document.getElementById('rec-log-list');\n"
"  var now = new Date();\n"
"  var ts = now.toTimeString().split(' ')[0];\n"
"  var entry = document.createElement('div');\n"
"  entry.className = 'log-entry';\n"
"  entry.innerHTML = '<span class=\"log-ts\">[' + ts + ']</span> '\n"
"    + '<span class=\"log-tool\">Touch #' + idx + '</span> '\n"
"    + '<span class=\"log-tool-detail\">(' + x + ', ' + y + ') on ' + w + 'x' + h + '</span>';\n"
"  el.appendChild(entry);\n"
"  el.scrollTop = el.scrollHeight;\n"
"}\n"
"\n"
"/* =================== Train Tab Logic =================== */\n"
"let trainCaptures = [];\n"
"let trainLabels = {};\n"
"let trainTree = {states: []};\n"
"let trainSelectedNode = null; // {type:'state',idx} or {type:'capture',stateIdx,capIdx}\n"
"\n"
"async function loadTrainSessions() {\n"
"  const r = await api('GET', '/api/train/sessions');\n"
"  if (!r) return;\n"
"  const sel = document.getElementById('train-session-select');\n"
"  sel.innerHTML = '<option value=\\'\\'>Select session...</option>';\n"
"  const sessions = Array.isArray(r) ? r : [];\n"
"  sessions.sort((a,b) => b.name.localeCompare(a.name));\n"
"  for (const s of sessions) {\n"
"    const opt = document.createElement('option');\n"
"    opt.value = s.name;\n"
"    opt.textContent = s.name + ' (' + s.count + ')';\n"
"    sel.appendChild(opt);\n"
"  }\n"
"}\n"
"\n"
"async function loadTrainSession() {\n"
"  const name = document.getElementById('train-session-select').value;\n"
"  if (!name) return;\n"
"  const r = await api('GET', '/api/train/session?name=' + encodeURIComponent(name));\n"
"  if (!r) return;\n"
"  trainCaptures = Array.isArray(r) ? r : [];\n"
"  trainCaptures.sort((a,b) => a.index - b.index);\n"
"  trainLabels = {};\n"
"  trainTree = {states: []};\n"
"  trainSelectedNode = null;\n"
"  // Build initial flat tree: each capture is its own unlabeled node\n"
"  renderTreeList();\n"
"  renderTrainDetail();\n"
"  document.getElementById('train-analyze-btn').disabled = (trainCaptures.length === 0);\n"
"  document.getElementById('train-build-btn').disabled = true;\n"
"}\n"
"\n"
"function renderTreeList() {\n"
"  const el = document.getElementById('train-tree-list');\n"
"  const sess = document.getElementById('train-session-select').value;\n"
"  if (trainCaptures.length === 0 && trainTree.states.length === 0) {\n"
"    el.innerHTML = '<div style=\\'color:var(--text-dim);padding:8px\\'>Load a session to begin</div>';\n"
"    return;\n"
"  }\n"
"  let html = '';\n"
"  if (trainTree.states.length > 0) {\n"
"    // Grouped tree view\n"
"    trainTree.states.forEach(function(state, si) {\n"
"      const isSel = trainSelectedNode && trainSelectedNode.type === 'state'"
"        && trainSelectedNode.idx === si;\n"
"      html += '<div class=\\'train-tree-node\\' style=\\'cursor:pointer;padding:3px 6px;"
"border-radius:4px;margin-bottom:1px;'"
"        + (isSel ? 'background:var(--bg-2);border-left:2px solid var(--accent)' : '')"
"        + '\\' onclick=\\'selectTreeNode(\"state\",' + si + ')\\'>';\n"
"      html += '<span style=\\'color:var(--accent);font-weight:600\\'>"
"        ' + escapeHtml(state.label) + '</span>';\n"
"      html += '<span style=\\'color:var(--text-dim);margin-left:4px\\'>("
"        ' + state.captures.length + ')</span>';\n"
"      html += '</div>';\n"
"      // Child captures\n"
"      state.captures.forEach(function(capIdx, ci) {\n"
"        const isCap = trainSelectedNode && trainSelectedNode.type === 'capture'"
"          && trainSelectedNode.stateIdx === si && trainSelectedNode.capIdx === ci;\n"
"        html += '<div style=\\'cursor:pointer;padding:2px 6px 2px 18px;"
"border-radius:4px;margin-bottom:1px;font-size:10px;'"
"          + (isCap ? 'background:var(--bg-2);border-left:2px solid var(--accent-2)' : '')"
"          + '\\' onclick=\\'selectTreeNode(\"capture\",' + si + ',' + ci + ')\\'>';\n"
"        var cap = trainCaptures.find(function(c){return c.index===capIdx;});\n"
"        html += '#' + capIdx;\n"
"        if (cap) html += ' <span style=\\'color:var(--text-dim)\\'>(' + cap.x + ',' + cap.y + ')</span>';\n"
"        html += '</div>';\n"
"      });\n"
"    });\n"
"  } else {\n"
"    // Flat list (before grouping)\n"
"    trainCaptures.forEach(function(cap, i) {\n"
"      const isSel = trainSelectedNode && trainSelectedNode.type === 'flat'"
"        && trainSelectedNode.idx === i;\n"
"      const label = trainLabels[cap.index] || '';\n"
"      html += '<div style=\\'cursor:pointer;padding:3px 6px;border-radius:4px;"
"margin-bottom:1px;font-size:11px;'"
"        + (isSel ? 'background:var(--bg-2);border-left:2px solid var(--accent)' : '')"
"        + '\\' onclick=\\'selectTreeNode(\"flat\",' + i + ')\\'>';\n"
"      html += '#' + cap.index;\n"
"      html += ' <span style=\\'color:var(--text-dim)\\'>(' + cap.x + ',' + cap.y + ')</span>';\n"
"      if (label) html += ' <span style=\\'color:var(--accent)\\'>' + escapeHtml(label) + '</span>';\n"
"      html += '</div>';\n"
"    });\n"
"  }\n"
"  el.innerHTML = html;\n"
"}\n"
"\n"
"function selectTreeNode(type, idx, capIdx) {\n"
"  if (type === 'capture') {\n"
"    trainSelectedNode = {type:'capture', stateIdx:idx, capIdx:capIdx};\n"
"  } else {\n"
"    trainSelectedNode = {type:type, idx:idx};\n"
"  }\n"
"  renderTreeList();\n"
"  renderTrainDetail();\n"
"}\n"
"\n"
"function renderTrainDetail() {\n"
"  const titleEl = document.getElementById('train-detail-title');\n"
"  const bodyEl = document.getElementById('train-detail-body');\n"
"  const sess = document.getElementById('train-session-select').value;\n"
"  if (!trainSelectedNode) {\n"
"    titleEl.textContent = 'Detail';\n"
"    bodyEl.innerHTML = '<div style=\\'color:var(--text-dim);font-size:11px\\'>"
"Select a state or capture from the tree</div>';\n"
"    return;\n"
"  }\n"
"  var sel = trainSelectedNode;\n"
"  if (sel.type === 'state') {\n"
"    // State detail: show label editor + all captures as thumbnails + actions\n"
"    var state = trainTree.states[sel.idx];\n"
"    titleEl.textContent = 'State: ' + state.label;\n"
"    var h = '<div style=\\'margin-bottom:8px\\'>';\n"
"    h += '<label style=\\'font-size:11px;color:var(--text-dim)\\'>State Label</label>';\n"
"    h += '<input id=\\'train-state-label\\' value=\\'' + escapeHtml(state.label)"
"      + '\\' style=\\'width:100%;background:var(--bg-0);color:var(--text);"
"border:1px solid var(--line);border-radius:6px;padding:4px 8px;font-size:12px;"
"margin-top:2px\\' onchange=\\'updateStateLabel(' + sel.idx + ',this.value)\\'>';\n"
"    h += '</div>';\n"
"    // Thumbnails\n"
"    h += '<div style=\\'font-size:11px;color:var(--text-dim);margin-bottom:4px\\'>"
"Captures (' + state.captures.length + ')</div>';\n"
"    h += '<div style=\\'display:flex;flex-wrap:wrap;gap:4px;margin-bottom:8px\\'>';\n"
"    state.captures.forEach(function(capIdx) {\n"
"      var imgUrl = '/api/train/image?session=' + encodeURIComponent(sess)"
"        + '&index=' + capIdx;\n"
"      h += '<img src=\\'' + imgUrl + '\\' style=\\'height:50px;border-radius:4px;"
"border:1px solid var(--line)\\' title=\\'#' + capIdx + '\\' loading=\\'lazy\\'>';\n"
"    });\n"
"    h += '</div>';\n"
"    // Actions\n"
"    h += '<div style=\\'font-size:11px;color:var(--text-dim);margin-bottom:4px\\'>"
"Actions (' + state.actions.length + ')</div>';\n"
"    state.actions.forEach(function(action, ai) {\n"
"      h += '<div style=\\'display:flex;gap:4px;align-items:center;margin-bottom:3px;"
"font-size:11px\\'>';\n"
"      h += '<span style=\\'color:var(--good)\\'>tap (' + action.x + ',' + action.y"
"        + ')</span>';\n"
"      h += '<input value=\\'' + escapeHtml(action.description || '')"
"        + '\\' placeholder=\\'description\\' style=\\'flex:1;background:var(--bg-0);"
"color:var(--text);border:1px solid var(--line);border-radius:4px;padding:2px 6px;"
"font-size:11px\\' onchange=\\'updateActionDesc(' + sel.idx + ',' + ai + ',this.value)\\'>';\n"
"      h += '</div>';\n"
"    });\n"
"    bodyEl.innerHTML = h;\n"
"  } else if (sel.type === 'capture') {\n"
"    // Single capture detail\n"
"    var state = trainTree.states[sel.stateIdx];\n"
"    var capIdx = state.captures[sel.capIdx];\n"
"    var cap = trainCaptures.find(function(c){return c.index===capIdx;});\n"
"    titleEl.textContent = 'Capture #' + capIdx;\n"
"    var imgUrl = '/api/train/image?session=' + encodeURIComponent(sess)"
"      + '&index=' + capIdx;\n"
"    var h = '<div style=\\'text-align:center;margin-bottom:8px\\'>';\n"
"    h += '<img src=\\'' + imgUrl + '\\' style=\\'max-width:100%;max-height:200px;"
"border-radius:6px;border:1px solid var(--line)\\' loading=\\'lazy\\'>';\n"
"    h += '</div>';\n"
"    if (cap) {\n"
"      h += '<div style=\\'font-size:11px;margin-bottom:4px\\'>';\n"
"      h += '<span style=\\'color:var(--text-dim)\\'>Touch: </span>';\n"
"      h += '<span style=\\'color:var(--good)\\'>(' + cap.x + ', ' + cap.y + ')</span>';\n"
"      h += ' <span style=\\'color:var(--text-dim)\\'>on ' + cap.w + 'x' + cap.h + '</span>';\n"
"      h += '</div>';\n"
"    }\n"
"    h += '<div style=\\'font-size:11px;margin-bottom:4px\\'>';\n"
"    h += '<span style=\\'color:var(--text-dim)\\'>State: </span>';\n"
"    h += '<span style=\\'color:var(--accent)\\'>' + escapeHtml(state.label) + '</span>';\n"
"    h += '</div>';\n"
"    var label = trainLabels[capIdx] || '';\n"
"    h += '<div style=\\'font-size:11px\\'>';\n"
"    h += '<span style=\\'color:var(--text-dim)\\'>VLM Label: </span>';\n"
"    h += '<span>' + escapeHtml(label || '(not analyzed)') + '</span>';\n"
"    h += '</div>';\n"
"    bodyEl.innerHTML = h;\n"
"  } else if (sel.type === 'flat') {\n"
"    // Flat capture detail (before grouping)\n"
"    var cap = trainCaptures[sel.idx];\n"
"    titleEl.textContent = 'Capture #' + cap.index;\n"
"    var imgUrl = '/api/train/image?session=' + encodeURIComponent(sess)"
"      + '&index=' + cap.index;\n"
"    var h = '<div style=\\'text-align:center;margin-bottom:8px\\'>';\n"
"    h += '<img src=\\'' + imgUrl + '\\' style=\\'max-width:100%;max-height:200px;"
"border-radius:6px;border:1px solid var(--line)\\' loading=\\'lazy\\'>';\n"
"    h += '</div>';\n"
"    h += '<div style=\\'font-size:11px;margin-bottom:4px\\'>';\n"
"    h += '<span style=\\'color:var(--text-dim)\\'>Touch: </span>';\n"
"    h += '<span style=\\'color:var(--good)\\'>(' + cap.x + ', ' + cap.y + ')</span>';\n"
"    h += ' <span style=\\'color:var(--text-dim)\\'>on ' + cap.w + 'x' + cap.h + '</span>';\n"
"    h += '</div>';\n"
"    var label = trainLabels[cap.index] || '';\n"
"    h += '<div style=\\'font-size:11px\\'>';\n"
"    h += '<span style=\\'color:var(--text-dim)\\'>VLM Label: </span>';\n"
"    h += '<span>' + escapeHtml(label || '(not analyzed)') + '</span>';\n"
"    h += '</div>';\n"
"    bodyEl.innerHTML = h;\n"
"  }\n"
"}\n"
"\n"
"function updateStateLabel(stateIdx, newLabel) {\n"
"  trainTree.states[stateIdx].label = newLabel;\n"
"  renderTreeList();\n"
"}\n"
"\n"
"function updateActionDesc(stateIdx, actionIdx, desc) {\n"
"  trainTree.states[stateIdx].actions[actionIdx].description = desc;\n"
"}\n"
"\n"
"async function analyzeAllCaptures() {\n"
"  const sess = document.getElementById('train-session-select').value;\n"
"  if (!sess || trainCaptures.length === 0) return;\n"
"  const btn = document.getElementById('train-analyze-btn');\n"
"  const prog = document.getElementById('train-progress');\n"
"  btn.disabled = true;\n"
"  prog.style.display = 'block';\n"
"  for (let i = 0; i < trainCaptures.length; i++) {\n"
"    const cap = trainCaptures[i];\n"
"    prog.textContent = 'Analyzing ' + (i+1) + '/' + trainCaptures.length + '...';\n"
"    const r = await api('POST', '/api/train/analyze', {session: sess, index: cap.index});\n"
"    if (r && r.label) {\n"
"      trainLabels[cap.index] = r.label;\n"
"    } else {\n"
"      trainLabels[cap.index] = '(failed)';\n"
"    }\n"
"    renderTreeList();\n"
"  }\n"
"  prog.textContent = 'Done! Click Build to group states.';\n"
"  btn.disabled = false;\n"
"  document.getElementById('train-build-btn').disabled = false;\n"
"  setTimeout(function() { prog.style.display = 'none'; }, 3000);\n"
"}\n"
"\n"
"function buildDecisionTree() {\n"
"  const groups = {};\n"
"  for (const cap of trainCaptures) {\n"
"    const label = (trainLabels[cap.index] || 'Unknown').trim();\n"
"    if (!groups[label]) groups[label] = {captures: [], actions: []};\n"
"    groups[label].captures.push(cap.index);\n"
"    if (cap.x || cap.y) {\n"
"      const exists = groups[label].actions.some(function(a) {\n"
"        return Math.abs(a.x - cap.x) < 20 && Math.abs(a.y - cap.y) < 20;\n"
"      });\n"
"      if (!exists) {\n"
"        groups[label].actions.push({x:cap.x, y:cap.y, w:cap.w, h:cap.h, description:''});\n"
"      }\n"
"    }\n"
"  }\n"
"  trainTree = {states: []};\n"
"  let idx = 0;\n"
"  for (const [label, data] of Object.entries(groups)) {\n"
"    trainTree.states.push({\n"
"      id: 'state_' + idx++,\n"
"      label: label,\n"
"      captures: data.captures,\n"
"      actions: data.actions\n"
"    });\n"
"  }\n"
"  trainSelectedNode = null;\n"
"  renderTreeList();\n"
"  renderTrainDetail();\n"
"  document.getElementById('train-save-tree-btn').disabled = false;\n"
"  document.getElementById('train-export-btn').disabled = false;\n"
"}\n"
"\n"
"async function saveDecisionTree() {\n"
"  await api('POST', '/api/train/tree', trainTree);\n"
"  var prog = document.getElementById('train-progress');\n"
"  prog.style.display = 'block';\n"
"  prog.textContent = 'Tree saved!';\n"
"  setTimeout(function() { prog.style.display = 'none'; }, 2000);\n"
"}\n"
"\n"
"async function loadDecisionTree() {\n"
"  const r = await fetch('/api/train/tree');\n"
"  if (!r.ok) return;\n"
"  try {\n"
"    const data = await r.json();\n"
"    if (data && data.states) {\n"
"      trainTree = data;\n"
"      trainSelectedNode = null;\n"
"      renderTreeList();\n"
"      renderTrainDetail();\n"
"      document.getElementById('train-save-tree-btn').disabled = false;\n"
"      document.getElementById('train-export-btn').disabled = false;\n"
"    }\n"
"  } catch(e) {}\n"
"}\n"
"\n"
"function exportTreeJson() {\n"
"  const json = JSON.stringify(trainTree, null, 2);\n"
"  const blob = new Blob([json], {type: 'application/json'});\n"
"  const url = URL.createObjectURL(blob);\n"
"  const a = document.createElement('a');\n"
"  a.href = url;\n"
"  a.download = 'decision_tree.json';\n"
"  a.click();\n"
"  URL.revokeObjectURL(url);\n"
"}\n"
"\n"
"// Load sessions when switching to train tab\n"
"(function() {\n"
"  const origSwitch = window.switchTab;\n"
"  window.switchTab = function(tab) {\n"
"    origSwitch(tab);\n"
"    if (tab === 'train') loadTrainSessions();\n"
"  };\n"
"})();\n"
"\n"
"function renderMessages(messages) {\n"
"  const el = document.getElementById('chat-history');\n"
"  const atBottom = el.scrollTop + el.clientHeight >= el.scrollHeight - 30;\n"
"  el.innerHTML = '';\n"
"  for (const m of messages) {\n"
"    if (m.role === 'system') continue;\n"
"    let cls = 'msg-' + m.role;\n"
"    let role = m.role === 'user' ? 'You' : m.role === 'assistant' ? 'AI' : (m.name || 'tool');\n"
"    const div = document.createElement('div');\n"
"    div.className = 'msg ' + cls;\n"
"    div.innerHTML = '<div class=\"msg-role\">' + escapeHtml(role) + '</div>' + escapeHtml(m.content || '');\n"
"    el.appendChild(div);\n"
"  }\n"
"  if (atBottom || messages.length !== lastMsgCount) {\n"
"    el.scrollTop = el.scrollHeight;\n"
"    lastMsgCount = messages.length;\n"
"  }\n"
"}\n"
"\n"
"function renderAutoState(autoRunning, gameRules) {\n"
"  const statusEl = document.getElementById('auto-status-text');\n"
"  const startBtn = document.getElementById('auto-start-btn');\n"
"  const stopBtn = document.getElementById('auto-stop-btn');\n"
"  const previewEl = document.getElementById('auto-rules-preview');\n"
"  if (autoRunning) {\n"
"    statusEl.textContent = 'Running';\n"
"    statusEl.className = 'value';\n"
"    startBtn.disabled = true;\n"
"    stopBtn.disabled = false;\n"
"  } else {\n"
"    statusEl.textContent = 'Stopped';\n"
"    statusEl.className = 'value stopped';\n"
"    startBtn.disabled = false;\n"
"    stopBtn.disabled = true;\n"
"  }\n"
"  if (gameRules && gameRules.trim()) {\n"
"    const preview = gameRules.length > 60 ? gameRules.substring(0, 60) + '...' : gameRules;\n"
"    previewEl.textContent = preview;\n"
"  } else {\n"
"    previewEl.textContent = 'Not set';\n"
"  }\n"
"}\n"
"\n"
"let rulesLoaded = false;\n"
"async function pollState() {\n"
"  const s = await api('GET', '/api/state');\n"
"  const settingsBtn = document.getElementById('open-settings-btn');\n"
"  if (!s) {\n"
"    if (settingsBtn) {\n"
"      settingsBtn.classList.add('disconnected');\n"
"      settingsBtn.title = 'Disconnected';\n"
"    }\n"
"    return;\n"
"  }\n"
"  if (settingsBtn) {\n"
"    settingsBtn.classList.remove('disconnected');\n"
"    settingsBtn.title = 'Connected | ' + (s.screen_width||0) + 'x' + (s.screen_height||0);\n"
"  }\n"
"  renderMessages(s.messages || []);\n"
"  renderAutoState(s.auto_running, s.game_rules);\n"
"  appendAutoLog(s.messages || []);\n"
"  if (s.recording !== undefined) {\n"
"    isRecording = s.recording;\n"
"    recordCount = s.record_count || 0;\n"
"    updateRecordUI();\n"
"  }\n"
"  if (!rulesLoaded && s.game_rules) {\n"
"    document.getElementById('rules-textarea').value = s.game_rules;\n"
"    rulesLoaded = true;\n"
"  }\n"
"  const ak = document.getElementById('cfg-api-key');\n"
"  if (!ak.value && s.config_api_key) ak.value = s.config_api_key;\n"
"  const md = document.getElementById('cfg-model');\n"
"  if (!md.value && s.config_model) md.value = s.config_model;\n"
"  const vm = document.getElementById('cfg-vision-model');\n"
"  if (!vm.value && s.config_vision_model) vm.value = s.config_vision_model;\n"
"  const bu = document.getElementById('cfg-base-url');\n"
"  if (!bu.value && s.config_base_url) bu.value = s.config_base_url;\n"
"}\n"
"\n"
"async function sendPrompt() {\n"
"  const el = document.getElementById('prompt-input');\n"
"  const text = el.value.trim();\n"
"  if (!text) return;\n"
"  el.value = '';\n"
"  await api('POST', '/api/prompt', {prompt: text});\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function clearHistory() {\n"
"  await api('POST', '/api/clear');\n"
"  autoLogMsgIndex = 0;\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function saveRules() {\n"
"  const rules = document.getElementById('rules-textarea').value;\n"
"  await api('POST', '/api/game-rules', {rules: rules});\n"
"  document.getElementById('summarize-status').textContent = 'Saved!';\n"
"  setTimeout(() => { document.getElementById('summarize-status').textContent = ''; }, 2000);\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function summarizeRules() {\n"
"  const statusEl = document.getElementById('summarize-status');\n"
"  statusEl.textContent = 'Summarizing...';\n"
"  const result = await api('POST', '/api/game-rules/summarize');\n"
"  if (result && result.rules) {\n"
"    document.getElementById('rules-textarea').value = result.rules;\n"
"    statusEl.textContent = 'Done! Review and save.';\n"
"  } else {\n"
"    statusEl.textContent = 'Failed to summarize.';\n"
"  }\n"
"  setTimeout(() => { statusEl.textContent = ''; }, 3000);\n"
"}\n"
"\n"
"async function startAuto() {\n"
"  await api('POST', '/api/auto/start');\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function stopAuto() {\n"
"  await api('POST', '/api/auto/stop');\n"
"  setTimeout(pollState, 300);\n"
"}\n"
"\n"
"async function applySettings() {\n"
"  const api_key = document.getElementById('cfg-api-key').value;\n"
"  const model = document.getElementById('cfg-model').value;\n"
"  const vision_model = document.getElementById('cfg-vision-model').value;\n"
"  const base_url = document.getElementById('cfg-base-url').value;\n"
"  await api('POST', '/api/config', {api_key, model, vision_model, base_url});\n"
"  closeSettingsModal();\n"
"}\n"
"\n"
"// Start polling\n"
"pollState();\n"
"pollTimer = setInterval(pollState, 2000);\n"
"\n"
"/* =================== Remote Panel Logic =================== */\n"
"let deviceWidth = 0, deviceHeight = 0;\n"
"let deviceCodec = null;\n"
"let jmuxerInstance = null;\n"
"let videoWs = null;\n"
"let controlWs = null;\n"
"let videoStarted = false;\n"
"let videoRotationDeg = 0;\n"
"let manualRotationLock = false;\n"
"var isFirefoxBrowser = /Firefox\\//.test(navigator.userAgent)\n"
"  || typeof InstallTrigger !== 'undefined';\n"
"var isChromiumBrowser = !isFirefoxBrowser\n"
"  && (/(Chrome|Chromium|Edg)\\//.test(navigator.userAgent)\n"
"      || (!!window.chrome && !!window.chrome.runtime));\n"
"\n"
"function toggleVideoRotation(e) {\n"
"  if (e && e.shiftKey) {\n"
"    manualRotationLock = false;\n"
"    updateVideoOrientation();\n"
"    return;\n"
"  }\n"
"  manualRotationLock = true;\n"
"  videoRotationDeg = videoRotationDeg === 0 ? -90 : 0;\n"
"  applyVideoLayout();\n"
"}\n"
"\n"
"function updateVideoOrientation() {\n"
"  if (manualRotationLock) {\n"
"    return;\n"
"  }\n"
"  if (!isChromiumBrowser) {\n"
"    if (videoRotationDeg !== 0) {\n"
"      videoRotationDeg = 0;\n"
"      applyVideoLayout();\n"
"    }\n"
"    return;\n"
"  }\n"
"  var video = document.getElementById('remote-video');\n"
"  var vw = video.videoWidth, vh = video.videoHeight;\n"
"  if (!vw || !vh || !deviceWidth || !deviceHeight) return;\n"
"  var needsRotation = (deviceHeight > deviceWidth) !== (vh > vw);\n"
"  var newDeg = needsRotation ? -90 : 0;\n"
"  if (newDeg === videoRotationDeg) return;\n"
"  videoRotationDeg = newDeg;\n"
"  applyVideoLayout();\n"
"}\n"
"\n"
"function applyVideoLayout() {\n"
"  var video = document.getElementById('remote-video');\n"
"  if (videoRotationDeg === 0) {\n"
"    video.classList.remove('rotated');\n"
"    video.style.transform = '';\n"
"    video.style.width = '';\n"
"    video.style.height = '';\n"
"    return;\n"
"  }\n"
"  var wrapper = document.getElementById('video-wrapper');\n"
"  var wW = wrapper.clientWidth, wH = wrapper.clientHeight;\n"
"  var ar = deviceWidth / deviceHeight;\n"
"  var visW, visH;\n"
"  if (ar < wW / wH) { visH = wH; visW = visH * ar; }\n"
"  else { visW = wW; visH = visW / ar; }\n"
"  video.classList.add('rotated');\n"
"  video.style.width = visH + 'px';\n"
"  video.style.height = visW + 'px';\n"
"  video.style.transform = 'translate(-50%, -50%) rotate(-90deg)';\n"
"}\n"
"\n"
"function initVideoWs() {\n"
"  const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"  const url = proto + '//' + location.host + '/ws/video';\n"
"  videoWs = new WebSocket(url);\n"
"  videoWs.binaryType = 'arraybuffer';\n"
"\n"
"  videoWs.onopen = () => {\n"
"    document.getElementById('remote-status').textContent = 'Video: Connected';\n"
"    videoStarted = false;\n"
"    document.getElementById('video-loading').style.display = 'flex';\n"
"  };\n"
"\n"
"  videoWs.onmessage = (evt) => {\n"
"    if (typeof evt.data === 'string') {\n"
"      try {\n"
"        const info = JSON.parse(evt.data);\n"
"        deviceWidth = info.width || 0;\n"
"        deviceHeight = info.height || 0;\n"
"        const newCodec = info.codec || 'h264';\n"
"        document.getElementById('remote-status').textContent =\n"
"          'Video: ' + deviceWidth + 'x' + deviceHeight + ' [' + newCodec.toUpperCase() + ']';\n"
"        resizeOverlay();\n"
"        // Initialize or reinitialize jmuxer when codec is first known or changes\n"
"        if (!jmuxerInstance || newCodec !== deviceCodec) {\n"
"          deviceCodec = newCodec;\n"
"          initJmuxer(newCodec);\n"
"        }\n"
"      } catch(e) {}\n"
"      return;\n"
"    }\n"
"    // Binary video data (H.264 or H.265) — already Annex-B from server\n"
"    if (jmuxerInstance) {\n"
"      var data = new Uint8Array(evt.data);\n"
"      try {\n"
"        jmuxerInstance.feed({ video: data });\n"
"      } catch(e) {\n"
"        console.error('jmuxer feed error:', e, 'size:', data.length);\n"
"      }\n"
"      // Sync playback position to live edge\n"
"      var vid = document.getElementById('remote-video');\n"
"      if (vid.buffered.length > 0) {\n"
"        var end = vid.buffered.end(vid.buffered.length - 1);\n"
"        if (end - vid.currentTime > 0.5) {\n"
"          vid.currentTime = end - 0.1;\n"
"        }\n"
"        if (vid.paused) vid.play().catch(function(){});\n"
"      }\n"
"      // keep current remote status text from connection/update events\n"
"    }\n"
"  };\n"
"\n"
"  videoWs.onclose = () => {\n"
"    document.getElementById('remote-status').textContent = 'Video: Disconnected';\n"
"    setTimeout(initVideoWs, 3000);\n"
"  };\n"
"\n"
"  videoWs.onerror = () => {\n"
"    videoWs.close();\n"
"  };\n"
"}\n"
"\n"
"function initControlWs() {\n"
"  const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"  const url = proto + '//' + location.host + '/ws/control';\n"
"  controlWs = new WebSocket(url);\n"
"\n"
"  controlWs.onclose = () => {\n"
"    setTimeout(initControlWs, 3000);\n"
"  };\n"
"\n"
"  controlWs.onerror = () => {\n"
"    controlWs.close();\n"
"  };\n"
"}\n"
"\n"
"function sendKey(key) {\n"
"  if (controlWs && controlWs.readyState === WebSocket.OPEN) {\n"
"    controlWs.send(JSON.stringify({type:'key', key: key}));\n"
"  }\n"
"}\n"
"\n"
"function sendTouch(action, clientX, clientY) {\n"
"  var dbg = document.getElementById('remote-status');\n"
"  if (!controlWs || controlWs.readyState !== WebSocket.OPEN) {\n"
"    dbg.textContent = 'Touch: WS not open';\n"
"    return;\n"
"  }\n"
"\n"
"  const video = document.getElementById('remote-video');\n"
"  // When Chrome rotation fix is active, use device dims; otherwise use video dims\n"
"  const vw = (videoRotationDeg !== 0) ? deviceWidth : (video.videoWidth || deviceWidth);\n"
"  const vh = (videoRotationDeg !== 0) ? deviceHeight : (video.videoHeight || deviceHeight);\n"
"  if (!vw || !vh) {\n"
"    dbg.textContent = 'Touch: no dimensions';\n"
"    return;\n"
"  }\n"
"\n"
"  // Use the video element's actual rendered box (not wrapper)\n"
"  // This avoids manual object-fit calculation and works regardless of layout ratio\n"
"  const videoRect = video.getBoundingClientRect();\n"
"\n"
"  const relX = clientX - videoRect.left;\n"
"  const relY = clientY - videoRect.top;\n"
"\n"
"  const normX = Math.max(0, Math.min(1, relX / videoRect.width));\n"
"  const normY = Math.max(0, Math.min(1, relY / videoRect.height));\n"
"\n"
"  const x = Math.min(Math.round(normX * vw), vw - 1);\n"
"  const y = Math.min(Math.round(normY * vh), vh - 1);\n"
"\n"
"  var msg = {type:'touch', action:action, x:x, y:y, w:vw, h:vh};\n"
"  controlWs.send(JSON.stringify(msg));\n"
"  // If recording, capture this touch for recording\n"
"  if (isRecording && action === 'down') {\n"
"    recordCount++;\n"
"    addRecordLogEntry(x, y, vw, vh, recordCount);\n"
"    api('POST', '/api/record/capture', {x: x, y: y, w: vw, h: vh, index: recordCount});\n"
"  }\n"
"  dbg.textContent = 'Touch: ' + action + ' ' + x + ',' + y + ' (' + vw + 'x' + vh + ')';\n"
"}\n"
"\n"
"function resizeOverlay() {\n"
"  const canvas = document.getElementById('touch-overlay');\n"
"  const wrapper = document.getElementById('video-wrapper');\n"
"  canvas.width = wrapper.clientWidth;\n"
"  canvas.height = wrapper.clientHeight;\n"
"}\n"
"\n"
"// Touch/mouse events on canvas overlay\n"
"(function() {\n"
"  const overlay = document.getElementById('touch-overlay');\n"
"  let isDown = false;\n"
"\n"
"  // Mouse events\n"
"  overlay.addEventListener('mousedown', (e) => {\n"
"    e.preventDefault();\n"
"    isDown = true;\n"
"    sendTouch('down', e.clientX, e.clientY);\n"
"  });\n"
"  overlay.addEventListener('mousemove', (e) => {\n"
"    if (!isDown) return;\n"
"    e.preventDefault();\n"
"    sendTouch('move', e.clientX, e.clientY);\n"
"  });\n"
"  overlay.addEventListener('mouseup', (e) => {\n"
"    if (!isDown) return;\n"
"    isDown = false;\n"
"    e.preventDefault();\n"
"    sendTouch('up', e.clientX, e.clientY);\n"
"  });\n"
"  overlay.addEventListener('mouseleave', (e) => {\n"
"    if (!isDown) return;\n"
"    isDown = false;\n"
"    sendTouch('up', e.clientX, e.clientY);\n"
"  });\n"
"\n"
"  // Touch events\n"
"  overlay.addEventListener('touchstart', (e) => {\n"
"    e.preventDefault();\n"
"    const t = e.touches[0];\n"
"    isDown = true;\n"
"    sendTouch('down', t.clientX, t.clientY);\n"
"  });\n"
"  overlay.addEventListener('touchmove', (e) => {\n"
"    e.preventDefault();\n"
"    const t = e.touches[0];\n"
"    sendTouch('move', t.clientX, t.clientY);\n"
"  });\n"
"  overlay.addEventListener('touchend', (e) => {\n"
"    e.preventDefault();\n"
"    isDown = false;\n"
"    const t = e.changedTouches[0];\n"
"    sendTouch('up', t.clientX, t.clientY);\n"
"  });\n"
"  overlay.addEventListener('touchcancel', (e) => {\n"
"    e.preventDefault();\n"
"    isDown = false;\n"
"    const t = e.changedTouches[0];\n"
"    sendTouch('up', t.clientX, t.clientY);\n"
"  });\n"
"\n"
"  window.addEventListener('resize', function() {\n"
"    resizeOverlay();\n"
"    if (videoRotationDeg !== 0) applyVideoLayout();\n"
"  });\n"
"})();\n"
"\n"
"function initJmuxer(codec) {\n"
"  const statusEl = document.getElementById('remote-status');\n"
"  if (typeof JMuxer === 'undefined') {\n"
"    statusEl.textContent = 'Error: jmuxer.js not loaded';\n"
"    return;\n"
"  }\n"
"\n"
"  if (typeof MediaSource === 'undefined') {\n"
"    statusEl.textContent = 'Error: MediaSource API not supported';\n"
"    return;\n"
"  }\n"
"\n"
"  // Check MSE codec support based on server-reported codec\n"
"  var mseCodec;\n"
"  var jmuxerVideoCodec;\n"
"  if (codec === 'h265') {\n"
"    mseCodec = 'video/mp4; codecs=\\\"hev1.1.6.L93.B0\\\"';\n"
"    jmuxerVideoCodec = 'H265';\n"
"  } else {\n"
"    mseCodec = 'video/mp4; codecs=\\\"avc1.640028\\\"';\n"
"    jmuxerVideoCodec = undefined;\n"
"  }\n"
"\n"
"  if (!MediaSource.isTypeSupported(mseCodec)) {\n"
"    statusEl.textContent = 'Error: ' + codec.toUpperCase() + ' codec not supported by browser';\n"
"    console.error('MSE codec not supported:', mseCodec);\n"
"    return;\n"
"  }\n"
"\n"
"  // Destroy previous instance if codec changed\n"
"  if (jmuxerInstance) {\n"
"    try { jmuxerInstance.destroy(); } catch(e) {}\n"
"    jmuxerInstance = null;\n"
"  }\n"
"\n"
"  try {\n"
"    var opts = {\n"
"      node: 'remote-video',\n"
"      mode: 'video',\n"
"      flushingTime: 100,\n"
"      fps: 30,\n"
"      debug: false,\n"
"      onReady: function() {\n"
"        statusEl.textContent = 'JMuxer ready [' + codec.toUpperCase() + '], waiting for video...';\n"
"      },\n"
"      onError: function(err) {\n"
"        console.error('JMuxer error:', err);\n"
"        statusEl.textContent = 'JMuxer error: ' + (err.message || err);\n"
"      }\n"
"    };\n"
"    if (jmuxerVideoCodec) {\n"
"      opts.videoCodec = jmuxerVideoCodec;\n"
"    }\n"
"    jmuxerInstance = new JMuxer(opts);\n"
"    statusEl.textContent = 'JMuxer initialized [' + codec.toUpperCase() + '], connecting...';\n"
"  } catch(e) {\n"
"    statusEl.textContent = 'JMuxer init error: ' + e.message;\n"
"    return;\n"
"  }\n"
"}\n"
"\n"
"// Initialize WebSockets (jmuxer is deferred until codec info received)\n"
"(function() {\n"
"  // Hide loading overlay only when video actually renders frames\n"
"  var remoteVid = document.getElementById('remote-video');\n"
"  remoteVid.addEventListener('timeupdate', function() {\n"
"    if (!videoStarted && remoteVid.currentTime > 0) {\n"
"      videoStarted = true;\n"
"      document.getElementById('video-loading').style.display = 'none';\n"
"      updateVideoOrientation();\n"
"    }\n"
"  });\n"
"  remoteVid.addEventListener('resize', function() {\n"
"    updateVideoOrientation();\n"
"  });\n"
"\n"
"  initVideoWs();\n"
"  initControlWs();\n"
"  resizeOverlay();\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif
